### ISSUE TITLE
[BUG] typo in  picamera2/examples/tensorflow /remove_background.py

### ISSUE THREAD

**Issue by scruss** [raspberrypi/picamera2#1165]
**Describe the bug**
Example code points to a tflite model that doesn't exist.

File: [remove_background.py](https://github.com/raspberrypi/picamera2/blob/296b19721b4c55559bde4dde9178d6ad9710aa91/examples/tensorflow/remove_background.py#L3)

Line 3 currently reads:
```py3
# Usage: ./remove_background.py --model deeplapv3.tflite --background thing.png
```

Should be changed to:
```py3
# Usage: ./remove_background.py --model deeplabv3.tflite --background thing.png
```

**Additional context**
Reported on the forum here: [picamera2/examples/tensorflow /remove_background.py - Raspberry Pi Forums](https://forums.raspberrypi.com/viewtopic.php?t=379517)

**Comment by davidplowman** [comment]
Thanks, I've pushed that change to our "next" branch, so it will appear in due course...!
