### ISSUE TITLE
[BUG] trying to access video stream through capture_stream.py results in Broken Pipe

### ISSUE THREAD

**Issue by arminveres** [raspberrypi/picamera2#140]
**Describe the bug**
Running the `capture_stream.py` and accessing it through e.g. VLC Media Player or [jsmpeg](https://github.com/phoboslab/jsmpeg) results in Broken Pipe error.
Accessing through browser works.

**To Reproduce**
I'm accessing my Pi from my main pc, and need the stream there, so I adjusted the ip among other things, but all round it should still work the same, At least I get the same result when using the standard script.
```python
import socket
import time

from picamera2.encoders import H264Encoder
from picamera2.outputs import FileOutput
from picamera2 import Picamera2

try:
    picam2 = Picamera2()
    video_config = picam2.video_configuration({"size": (1280, 720)})
    picam2.configure(video_config)
    picam2.encoder = H264Encoder(1000000, False)
    picam2.start()

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        # sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        # localhost of the raspberry
        # sock.bind(("0.0.0.0", 10001))
        # address accessible to workstation
        sock.bind(("10.42.0.2", 10001))
        sock.listen(5)

        conn, addr = sock.accept()
        print(f"connection accepted, addr: {addr}, conn: {conn}")

        stream = conn.makefile("wb")
        picam2.encoder.output = FileOutput(stream)
        picam2.start_encoder()
        # picam2.start()

        print(sock.getsockname())
        time.sleep(60)
        # while True:
        #     time.sleep(1)

        picam2.stop()
        picam2.stop_encoder()
        conn.close()
        exit(0)

except Exception as e:
    print(f"\nError occured: {e}\n")
```

**Expected behaviour**
I expect for the videostream to appear.

**Console Output, Screenshots**
```
BrokenPipeError: [Errno 32] Broken pipeException in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/poncha_pi/.local/lib/python3.9/site-packages/picamera2/encoders/v4l2_encoder.py", line 173, in thread_poll
    self.output.outputframe(b, keyframe)
  File "/home/poncha_pi/.local/lib/python3.9/site-packages/picamera2/outputs/fileoutput.py", line 36, in outputframe
    self._fileoutput.write(frame)
  File "/usr/lib/python3.9/socket.py", line 722, in write
    return self._sock.send(b)
BrokenPipeError: [Errno 32] Broken pipe
```

**Hardware :**
I'm using a Pi 4B and a v2 Camera.

**Comment by chrisruk** [comment]
Thanks for the bug report.

From what I can tell the broken pipe appears when the connection closes, I need to fix that.

I'm also struggling to get vlc to display the stream.

I use the video program, 'mpv' and do:

```
mpv tcp://IP:10001
```

I'll try and do more digging into why vlc doesn't display the stream

**Comment by chrisruk** [comment]
Can you try this from a terminal:

```
vlc tcp/h264://IP:10001
```

It played the stream for me

**Comment by davidplowman** [comment]
We do know that recent versions of VLC cannot play raw h.264 streams properly. This is true even of files, not just network streams. I don't know exactly why or when it got broken, but older versions used to have no trouble. This is why I generally recommend something like ffplay these days.

**Comment by arminveres** [comment]
> Can you try this from a terminal:
> 
> ```
> vlc tcp/h264://IP:10001
> ```
> 
> It played the stream for me

Thanks a lot, that worked for me.
You can disregard the JSMpeg issue for now, I didn't notice that it only accepted Mpeg1 encoded streams.


> We do know that recent versions of VLC cannot play raw h.264 streams properly. This is true even of files, not just network streams. I don't know exactly why or when it got broken, but older versions used to have no trouble. This is why I generally recommend something like ffplay these days.

Good to know, thanks for that as well.

**Comment by chrisruk** [comment]
You shouldn't get a brokenpipe error anymore if the connection is closed by the user.

Closing for now, please reopen if there's still any remaining issues
