### ISSUE TITLE
[SUGGESTION] Please, mention need to enable Glamor in the instructions

### ISSUE THREAD

**Issue by ibmua** [raspberrypi/picamera2#142]
At least on Pi 3 B, it doesn't work if glamor is not enabled and this is nowhere to be found in the github instructions.

**Comment by davidplowman** [comment]
Thanks for raising this, we'll get that fixed. Actually the documentation will be undergoing a complete re-write (turning it into "official documentation") which is why I've avoided having a separate issue category for it, but I agree that simple things like this should be fixed.

**Comment by davidplowman** [comment]
A documentation update has been merged now, so I'll close this. Thanks!
