### ISSUE TITLE
[HOW-TO]  How to use the autofocus control

### ISSUE THREAD

**Issue by ketai-dhr** [raspberrypi/picamera2#180]
**Describe what it is that you want to accomplish**
How to use the autofocus control.

**Describe alternatives you've considered**
In your C++ libcamera library, I remember that it supports autofocus control（AfTrigger）, but I can't find this control in the picamera2 packaged by it, can you tell me his name?

**Additional context**
![ssss](https://user-images.githubusercontent.com/60175845/174993839-0d7b804a-9d42-4830-be8b-5738c027ea8d.jpg)

**Comment by tvoverbeek** [comment]
I guess you are using the Arducam autofocus camera.
They have their own modified libcamera and my guess is that AfTrigger is not exposed in their their bindings.
Their libcamera version might also be out of step with the RPi version.
Anyway AfTrigger is not available in the RPi libcamera version (at least it was not a few weeks ago when I last checked)

**Comment by davidplowman** [comment]
Sorry, I'm afraid that's correct, autofocus is not currently available in the Raspberry Pi versions of these libraries.

**Comment by ketai-dhr** [comment]
@davidplowman 
Well, thanks for your reply.

**Comment by surak** [comment]
When you have the libcamera from Arducam installed, this works in python: picam2.set_controls({"AfTrigger": 0})

**Comment by millermuttu** [comment]
When we trigger Aftirigger using the below code,
'''
picam2.set_controls({"AfTrigger": 0})
'''

How do you wait until the autofocus happens or know that image is focused?

**Comment by davidplowman** [comment]
This answer is specific to Raspberry Pi camera modules that support autofocus (namely the Camera Module 3). I don't know if it works with Arducam modules or software; if it doesn't you would need to go to Arducam for support.

After triggering an autofocus cycle you need to watch the `AfState` metadata so discover when it's finished. This is actually all done for you if you call `picam2.autofocus_cycle()`.
