### ISSUE TITLE
What configuration for IP Camera frame flow

### ISSUE THREAD

**Issue by shineworld** [raspberrypi/picamera2#183]
I'm developing a Raspberry PI 4-based IM477 IP camera using Picamera2.
The Raspberry has a thread that continues to get frame image and encode it to JPEG.
A socket receives the GRAB command and the current threaded acquired frame is sent back to the consumer client.
The frame resolution and camera start are managed between a START_CAMERA TCP command before requesting GRAB.

Now the question.
For a continuous frame get to Picamera2 what is the best configuration way?

Preview or Still or something other?
What I want is the fastest way to get continuous frames JPEG-Encoded to be shown in a Windows program that uses
OpenCV to elaborate frame flow and show it on screen (as a video).

A moment I've used:
```
 self.__camera.configure(self.__camera.preview_configuration(main={"format": 'RGB888', "size": (camera_width, camera_height)}))
 self.__camera.start()
 self.__camera_controls = CAMERA_CONTROLS_DEFAULT
 self.__frame_acquire_thread_exit_event = threading.Event()
 self.__frame_acquire_thread = threading.Thread(target=self.__frame_acquire_thread_main, args=(None,))
 self.__frame_acquire_thread.start()
```
```
    # == BEG: frame acquire thread implementation
    #
    def __frame_acquire_thread_main(self, args):
        while not self.__frame_acquire_thread_exit_event.is_set():
            #time.sleep(0.0001)
            try:
                frame = self.__camera.capture_array()
                if frame is None:
                    continue
                if IMAGE_ENCODE_WITH_SJPEG:
                    frame_enc = np.frombuffer(sjpeg.encode_jpeg(frame, quality=IMAGE_ENCODE_SJPEG_RATIO, colorspace='BGR', fastdct=IMAGE_ENCODE_SJPEG_FASTDCT), dtype=np.ubyte)
                else:
                    _, frame_enc = cv2.imencode(IMAGE_ENCODE_FORMAT, frame, IMAGE_ENCODE_FLAGS)
                self.__frame = frame_enc.copy()
                self.__frame_acquire_count += 1
            except:
                pass

    #
    # == END: frame acquire main thread implementation
```
There is a way with Picamera2 to choose the UNICAM camera sensor format?
At moment, for example, with the main preview width:height 640x480 Picamera2 uses a larger UNICAM format where IMX477 support also 640:480.

**Comment by davidplowman** [comment]
> Preview or Still or something other? What I want is the fastest way to get continuous frames JPEG-Encoded to be shown in a Windows program that uses OpenCV to elaborate frame flow and show it on screen (as a video).

It probably doesn't make very much difference as the image resolution and JPEG encoding may be the limiting factors. Maybe avoid `still_configuration()` because that might be slower . You could try `video_configuration()` which might have some benefits, but I think any differences would be marginal.

> 
> ...
> 
> There is a way with Picamera2 to choose the UNICAM camera sensor format? At moment, for example, with the main preview width:height 640x480 Picamera2 uses a larger UNICAM format where IMX477 support also 640:480.

You can force a particular camera mode by asking for a raw stream (this does not cause any extra processing). Type `libcamera-hello --list-cameras` into a terminal to see what formats and resolutions are supported. You could then use them like this:
```
main = {"format": 'RGB888', "size": (camera_width, camera_height)}
raw = {"format": "SRGGB12_CSI2P", "size": (2028, 1520)}
config = self.__camera.preview_configuration(main, raw=raw)
self.__camera.configure(config)
```

**Comment by davidplowman** [comment]
Yes, I'm afraid those warnings/errors are normal. There was some work going on to try and get rid of them because they are not important, I will have to check what has happened!

**Comment by shineworld** [comment]
With the new libcamera (v0.0.0+3700-f30ad033) and Picamera2 (0.2.3) any WARN and ERROR disappeared.
