### ISSUE TITLE
[DOCUMENTATION]Correction to note

### ISSUE THREAD

**Issue by andrum99** [raspberrypi/picamera2#198]
Section 3.2 on page 11 has a note which says `The NULL preview is really just such as event loop that we need to run if there is not one being run by the GUI framework (Qt usually).` This should probably say:

`The NULL preview is really just such as event loop that we need to run if there is not one being run by a real preview window.` 

Alternatively, it probably makes more sense to say this:

`Each type of preview window implements an event loop to dequeue frames from the camera`.

The remarks about event loops belongs in section 3.1. I'm not sure that an admonition is necessary - perhaps just a remark that the preview windows implement an event loop in its own paragraph within setion 3.1 would be more appropriate?

**Comment by davidplowman** [comment]
Thanks, I've reworded this along these lines. It will appear in the next release.
