### ISSUE TITLE
[DOCUMENTATION]Spelling - frame rate

### ISSUE THREAD

**Issue by andrum99** [raspberrypi/picamera2#200]
Section 3.3 on page 11 has `framerates` in the second item in the first list. Per lexico.com this should be `frame rates`. (Neither exists in Merriam-Webster's online dictionary).

**Comment by andrum99** [comment]
I've come across other instances of this - you would probably want to run a search and replace if you decide to change this spelling.

**Comment by davidplowman** [comment]
Not sure about this, "framerate" (one word) seems to be used quite a bit in the video/computer world, rightly or (more probably) wrongly. I may wait and see what the documentation folks here think about it. Thanks!

**Comment by aallan** [comment]
The style guide has nothing to say on the issue, so we don't have a formal pre-existing position on this one. For my own sake, while formally it should be "frame rate" I think "framerate" an accepted industry term and is fine.
