### ISSUE TITLE
[DOCUMENTATION]

### ISSUE THREAD

**Issue by sandyol55** [raspberrypi/picamera2#210]
**This form is ONLY for reporting issues with https://datasheets.raspberrypi.com/camera/picamera2-manual-draft.pdf**

**Please only report one documentation bug per issue!**

**Describe the problem**
Page 16 Section 4.2.1.4
Code snippet describing lores preview has typo in the import line.

**Suggested Improvement**
Replace:-
`from picamera import Picamera2`
 

with:-
`from picamera2 import Picamera2`

**Comment by davidplowman** [comment]
Thanks, I've fixed this now and it will be in the next documentation release!
