### ISSUE TITLE
[DOCUMENTATION] 8.2.1 Event loop callback

### ISSUE THREAD

**Issue by sandyol55** [raspberrypi/picamera2#214]
Final para on page 38 

_It is not possible to do processing on frames that will be recorded as video but not when they are displayed, or vice
versa, as these two processes run in parallel_. Though we note that an application could display a different stream from
the one it encodes (it might display the "main" stream and encode the "lores" version), and apply processing only to one
of them which would simulate this effect.

Took a while to get my head around the first sentence. (Maybe just me!!)

Perhaps clearer (?) if reworded along the lines of.......

It is not possible to do processing on frames that will be recorded as video, and not to do the same processing on the frames when they are displayed, or vice versa, as these two processes run in parallel. Though we note that an application could display a different stream from the one it encodes (it might display the "main" stream and encode the "lores" version), and apply processing only to one of them which would simulate this effect.

**Comment by davidplowman** [comment]
Yes I agree, it was one of those things that came out when I was in "spend several days doing lots and lots of typing" mode. I've updated our internal documentation repo along the lines suggested so that will appear when we next update the published version. Thanks!
