### ISSUE TITLE
[BUG] Monochrome formats are valid for raw captures

### ISSUE THREAD

**Issue by 6by9** [raspberrypi/picamera2#230]
**Describe the bug**
https://forums.raspberrypi.com/viewtopic.php?p=2022829#p2022829
OV9281 or other monochrome sensor producing Y8, Y10. Y10P, Y12, Y12P, etc.
[check_stream_config](https://github.com/raspberrypi/picamera2/blob/main/picamera2/picamera2.py#L493) checks for ```if not self.is_Bayer(format):```, and mono formats aren't Bayer, therefore fail.

**To Reproduce**
See thread

**Expected behaviour**
Mono raw captures

**Comment by davidplowman** [comment]
I've fixed this on the "next" branch now, so you ought to be able to request raw streams correctly once that has been released.

The only catch is that libcamera is actually a bit broken in this area too. I've submitted the [necessary patches](https://patchwork.libcamera.org/project/libcamera/list/?series=3371), but obviously we'll have to wait for those to come through as well before things really work correctly.
