### ISSUE TITLE
[OTHER] How to set ISO?

### ISSUE THREAD

**Issue by eat-sleep-code** [raspberrypi/picamera2#237]
**Please only include one item/question/problem per issue!**

In the original Picamera library, you could set the ISO value using `camera.iso = 100` 

How is this accomplished in PiCamera2?

**Comment by davidplowman** [comment]
Use need to set the gain (or actually the analogue gain) instead:
```
picam2.set_controls({"AnalogueGain": 2.0})
```
I think the ISO is mostly treated as being the gain * 100, so an ISO of 100 was a gain of 1.0, and the above gives you an "ISO" of 200.

**Comment by Cande8a** [comment]
@davidplowman is there a max value for Analogue Gain? I can't find that information. Thanks!
