### ISSUE TITLE
[DOCUMENTATION] Small typo in section 8.3

### ISSUE THREAD

**Issue by callidus** [raspberrypi/picamera2#245]
**Describe the problem**
At the base of page 40 (8.3. Pixel Formats and Memory Considerations) the text `Some use more considerably more memory than others,` appears. It looks like this is a typo.

**Suggested Improvement**
`Some use considerably more memory than others,`

**Additional context**
at the start of section `8.3. Pixel Formats and Memory Considerations`

**Comment by davidplowman** [comment]
Thanks for that, I've corrected that and it will appear with the next documentation release.
