### ISSUE TITLE
[HOW-TO] Multiple cameras using CM4 & Picamera2

### ISSUE THREAD

**Issue by neil-benn** [raspberrypi/picamera2#258]
Hello,

  I'm running a CM4 with libcamera; the libcamera apps can capture from both cameras using the command line apps.  I'm now trying to capture from both cameras using picamera2 but I can't see how to specify which camera to connect to.  Is this available in picamera2?

  I could look at using v4l2 or picking through the code from the RPi libcamera-apps to adapt into a python library but that would take much longer to handle and be duplicating efforts made here.

Thanks.

Regards,

Neil

**Comment by davidplowman** [comment]
Hi, the _Picamera2_ constructor takes a `camera_num` argument, defaulting to zero, which should in theory specify which camera to use.

The catch is that I haven't ever got round to trying this on a CM4. With luck and a following wind, it might work like libcamera-apps do, i.e. you can start separate Python interpreters and attach each to a different camera (there is no real handling of dual cameras within libcamera itself). Though the usual rule applies that all software is broken until you've tested it. I'd be interested to hear what happens...

**Comment by neil-benn** [comment]
Hello,

  Great news - I'm on the case and I'll see what happens!

Cheers,

Neil

--

Neil Benn MSc
Ziath Ltd
Phone: +44 (0) 1223 855021
http://www.ziath.com<http://www.ziath.com/>

Please consider the environment before printing this email.

Follow us on Facebook<http://www.facebook.com/ziathltd>, Twitter<http://www.twitter.com/ziath_ltd> or LinkedIn<http://www.linkedin.com/company/ziath-ltd>

IMPORTANT NOTICE: This message, including any documents, is intended only for the use of the individual or entity to which it is addressed, and may contain information that is privileged, confidential and exempt from disclosure under applicable law. If the reader of this message is not the intended recipient, or the employee or agent responsible for delivering the message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify Ziath Ltd immediately by email at ***@***.******@***.***>. Thank you.

________________________________

**Comment by neil-benn** [comment]
Hello,

  I tested this today and accessing one camera in one process worked just fine using picamera2 on cam 0 and cam 1.  I used a still config, started the camera and took 20 or 30 images without a problem.

  Thanks

Cheers,

Neil

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by CorvetteCole** [comment]
this should probably be closed. camera interface works just fine on CM4 with multiple processes even

**Comment by davidplowman** [comment]
Thanks!
