### ISSUE TITLE
[HOW-TO] how to capture in BGR ?

### ISSUE THREAD

**Issue by zoldaten** [raspberrypi/picamera2#260]
hi!
in Picamera there was something like this:
```
for frame in camera.capture_continuous(capture, format="bgr", use_video_port=True,
                                       resize=(img_width,img_height)):
```
for Picamera2 there it goes:
```
while True:    
    origin_img = camera.capture_array()
    origin_img = cv2.cvtColor(origin_img, cv2.COLOR_BGRA2RGB)
```
i have to convert each frame to BGR.
Perhaps, there is a better way to do that ?

I thied camera.format = "RGB888" but failed.

**Comment by Tim-Brown-NZ** [comment]
Have you tried specifying the format in the definition of main when creating the configuration. Something like:
_config = self.picam2.create_preview_configuration(main={"format": "RGB888"}) 
self.picam2.configure(config)
self.picam2.start()_

**Comment by zoldaten** [comment]
got it!
