### ISSUE TITLE
CameraConfiguration' object is not callable

### ISSUE THREAD

**Issue by SaailN** [raspberrypi/picamera2#287]
While running the python script with configuration object i m getting the following error. Seems like object is not callable.
review_config = picam2.preview_configuration()
TypeError: 'CameraConfiguration' object is not callable
![error2](https://user-images.githubusercontent.com/40292489/187019575-120c3958-d5dd-4754-8b85-33b6bc9ede6a.png)

**Comment by Tim-Brown-NZ** [comment]
In the latest release all the xxx_configuration methods were renamed to to create_xxx_configuration.
So you need to call create_preview_configuration() as in the updated example here:
https://github.com/raspberrypi/picamera2/blob/main/examples/preview.py

**Comment by SaailN** [comment]
Thanks @Tim-Brown-NZ
