### ISSUE TITLE
Error Attribute Libcamera

### ISSUE THREAD

**Issue by Aaronngp** [raspberrypi/picamera2#303]
Can't run example code (tuning_file.py), because libcamera give an error

I try to use the camera to take screenshots but I get an attribute error. 

This didn't happen before, after several days without using the camera now this error has come out. 

Console output: AttributeError: type object 'libcamera._libcamera.ColorSpace' has no attribute 'Jpeg'

I'm using RPI 4 and camera pi noir v2.1. I try this code in Thonny.

**Comment by davidplowman** [comment]
Hi, the libcamera API has changed so you need to update Picamera2 to match. Updating to the latest version (currently 0.3.3) should fix this.

Moving forward, we're telling people that they can install Picamera2 using `sudo apt install -y python3-picamera2`. You will need to uninstall the pip version first, however. Then you can update your software with `sudo apt update` and `sudo apt upgrade` and you'll always get compatible versions of libcamera and Picamera2.

**Comment by faeq123** [comment]
whats the command to uninstall the pip version?

**Comment by davidplowman** [comment]
I think it's `pip3 uninstall picamera2`

**Comment by faeq123** [comment]
thank you soo much it worked

**Comment by davidplowman** [comment]
Great! I think I'll close this one now - please feel free to post a new issue if anything else comes up. Thanks!

**Comment by Alpha-Badger** [comment]
@davidplowman 

> Hi, the libcamera API has changed so you need to update Picamera2 to match. Updating to the latest version (currently 0.3.3) should fix this.
> 
> Moving forward, we're telling people that they can install Picamera2 using `sudo apt install -y python3-picamera2`. You will need to uninstall the pip version first, however. Then you can update your software with `sudo apt update` and `sudo apt upgrade` and you'll always get compatible versions of libcamera and Picamera2.

Hello, 

`sudo apt install -y python3-picamera2` gives me the following message:

**rhinosd@raspberrypi:~ $ sudo apt install -y python3-picamera2
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-picamera2 is already the newest version (0.3.3-1).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
python3-picamera2 : Depends: python3-libcamera but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).**

Obviously the next thing I should do is `install python3-libcamera`. However, the solution to another issue I have with my Arducam conflicts with doing this. Here is a link that outlines what I am experiencing: https://forum.arducam.com/t/how-is-it-possible-to-get-autofocus-working-along-with-picamera2-for-imx519/3460/6

"If you have python3-libcamera installed, this will cause you to use the official libcamera, which has no focus control"

They explicitly mention that to not use install python3-libcamera. How can I use PiCamera2, Arducam, and implement their functionalities via Python? Perhaps it's out of your purview as it may be a question for Arducam. However, I feel as though more synergy between PiCamera2 and Arducam is in order. Could that be something that is addressed with them?

**Comment by davidplowman** [comment]
Hi, yes I think it's a question for Arducam, really. Probably the best solution would be for them to implement autofocus properly as part of the libcamera framework, but obviously there would be more work involved in this.
