### ISSUE TITLE
[HOW-TO] Change AfSpeed

### ISSUE THREAD

**Issue by jackzed** [raspberrypi/picamera2#305]
I am interested in speeding up the 64MP camera autofocus time. In the libcamera documentation I can see there is an option to change the speed (AfSpeed). I have been unsuccessful in trying to implement this, any help or suggestions would be greatly appreciated. Cheers

**Comment by davidplowman** [comment]
Hi, I've answered this question in your [forum post](https://forums.raspberrypi.com/viewtopic.php?t=339913#p2036261). Sorry not to be more helpful on this one but it's Arducam's software and I think they probably need to help you with it.
