### ISSUE TITLE
raw format in start_recording? 

### ISSUE THREAD

**Issue by tf4ong** [raspberrypi/picamera2#326]
Is it possible to add raw format in start_recording? 

I would like to have functionality similar to libcamera-raw with the output of pts timestamps

Is it possible

**Comment by davidplowman** [comment]
@chrisruk I'm wondering whether we should make the `encode` function in the `Encoder` base class (in `encoder.py`) call the `outputframe` method (rather than just `pass`), and then this might "just work". What do you think?

**Comment by davidplowman** [comment]
There's a PR in progress for this: https://github.com/raspberrypi/picamera2/pull/329
