### ISSUE TITLE
[BUG] python3-libcamera not available in venv

### ISSUE THREAD

**Issue by mnbf9rca** [raspberrypi/picamera2#341]
**Describe the bug**
When running from a venv, libcamera is not available. It works fine when not in venv.

**To Reproduce**
1. fresh Raspbian 32bit bullseye installation, after running both `apt-get dist-upgrade` and `apt-get upgrade`
2. create a venv e.g. `python3 -m venv venv`
3. activate `source ./venv/bin/activate`
4. install build dependencies: `sudo apt-get install -y libpcap-dev python3-libcamera`
5. upgrade pip to v22: `sudo python3 -m pip install --upgrade pip` 
6. install picamera2 in venv: `pip install picamera2`
7. copy the `mjpeg_server.py` demo to local machine: `wget https://raw.githubusercontent.com/raspberrypi/picamera2/main/examples/mjpeg_server.py`
8. run the server: `python3 mjpeg_server.py`

**Expected behaviour**
Streaming server should start

**Console Output, Screenshots**
```python
(venv) pi@mariner:~ $ python3 mjpeg_server.py
Traceback (most recent call last):
  File "/home/pi/mjpeg_server.py", line 13, in <module>
    from picamera2 import Picamera2
  File "/home/pi/venv/lib/python3.9/site-packages/picamera2/__init__.py", line 1, in <module>
    from .configuration import CameraConfiguration, StreamConfiguration
  File "/home/pi/venv/lib/python3.9/site-packages/picamera2/configuration.py", line 1, in <module>
    from .controls import Controls
  File "/home/pi/venv/lib/python3.9/site-packages/picamera2/controls.py", line 4, in <module>
    from libcamera import ControlType, Size, Rectangle
ModuleNotFoundError: No module named 'libcamera'
```

**Hardware :**
Camera: original Raspberry PI NoIR camera

```bash
pi@mariner:~ $ cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 1
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 2
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 3
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

Hardware        : BCM2711
Revision        : c03115
Serial          : 10000000c572d4af
Model           : Raspberry Pi 4 Model B Rev 1.5
pi@mariner:~ $ uname -a
Linux mariner 5.15.61-v7l+ #1579 SMP Fri Aug 26 11:13:03 BST 2022 armv7l GNU/Linux
pi@mariner:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
pi@mariner:~ $ cat /etc/debian_version
11.5
```

**Additional context**
apt-get reports the library is already installed:
```bash
(venv) pi@mariner:~ $ sudo apt-get install python3-libcamera
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-libcamera is already the newest version (0~git20220826+3fad116f-1).
The following package was automatically installed and is no longer required:
  libfuse2
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

if you leave the venv it works:
```bash
(venv) pi@mariner:~ $ deactivate
pi@mariner:~ $ python3 mjpeg_server.py
[9:44:23.932952611] [3178]  INFO Camera camera_manager.cpp:293 libcamera v0.0.0+3866-0c55e522
[9:44:23.960313915] [3179]  WARN RPI raspberrypi.cpp:1258 Mismatch between Unicam and CamHelper for embedded data usage!
[9:44:23.961292189] [3179]  INFO RPI raspberrypi.cpp:1374 Registered camera /base/soc/i2c0mux/i2c@1/imx219@10 to Unicam device /dev/media3 and ISP device /dev/media1
[9:44:23.964590769] [3178]  INFO Camera camera.cpp:1035 configuring streams: (0) 640x480-XBGR8888
[9:44:23.965081322] [3179]  INFO RPI raspberrypi.cpp:761 Sensor: /base/soc/i2c0mux/i2c@1/imx219@10 - Selected sensor format: 640x480-SBGGR10_1X10 - Selected unicam format: 640x480-pBAA
```

**Comment by davidplowman** [comment]
@chrisuk Hi Chris, just wondering if by any change you've ever used "venv"s? (I must confess that I know nothing about them...)

**Comment by davidplowman** [comment]
Actually I've just done a web search. It seems you need to use the ``--system-site-packages`` option when you create the venv. Please see https://docs.python.org/3/library/venv.html.

**Comment by chrisruk** [comment]
Sorry was afk, yep that's what I've used before, otherwise you'd have to install libcamera within the venv, which might be tricky as I don't think there's a PyPi version.

**Comment by davidplowman** [comment]
@mnbf9rca I think `--system-site-packages` sounds like the answer. Does that resolve this for you? Thanks!

**Comment by mnbf9rca** [comment]
Yes! I've never even noticed that option before. Thanks so much. Perhaps worth adding to the documentation?

**Comment by DennisSchulmeister** [comment]
Hello,

Just stumbling upon the same problem. While `--system-site-packages` works around the problem, this not a good solution. Because the very purpose of python environments is to be isolated from the system-installed packages. The real solution would in deed be a pypi version of the libcamera module pulled in by picamera2 as a regular dependency.

KR, Dennis

**Comment by eya1903** [comment]
> Actually I've just done a web search. It seems you need to use the `--system-site-packages` option when you create the venv. Please see https://docs.python.org/3/library/venv.html.

I confirm, it works guys. Thank you saved me !

**Comment by Wences1024** [comment]
I had the same issue D: !!!!  and I double confirm, it works by creating a new environment with "--system-site-packages". I am working on a project using openCV with the Raspberry camera.
These were the steps I followed:

#Create a virtual environment
python3 -m venv --system-site-packages new_env

#Activate the new environment
source new_env/bin/activate

#Update pip
pip install --upgrade pip

#Install mediapipe
pip install mediapipe

#Install OpenCV
pip install opencv-python

#Check if you have all the libraries available
pip list


You must see "picamera2" in the list when using "pip list"
