### ISSUE TITLE
[SUGGESTION] Option to show fps, exposure, etc in preview window title, similar to libcamera-apps

### ISSUE THREAD

**Issue by vincentneo** [raspberrypi/picamera2#347]
In libcamera-apps, preview windows have it's window title with live updating info, probably it would be nice to have a convenient way of having the same thing for QTGL previews here as well?

![image](https://user-images.githubusercontent.com/23420208/194744055-a9cb9466-944c-43f7-9d0e-64f3a572e1a2.jpeg)
(Image from https://www.raspberrypi.com/documentation/accessories/camera.html)

**Comment by davidplowman** [comment]
Hi, yes I think I wondered about that but maybe it would be a useful feature. In the meantime you could try this kind of thing as a workaround:
```
from picamera2 import Picamera2
from picamera2.previews import QtGlPreview

def callback(request):
    preview.qpicamera2.setWindowTitle(f"{request.get_metadata()['ExposureTime']}")

picam2 = Picamera2()
preview = QtGlPreview()
picam2.pre_callback = callback
picam2.start_preview(preview)
picam2.start()
```

**Comment by davidplowman** [comment]
I've made some changes here: https://github.com/raspberrypi/picamera2/pull/369

It's not the same as libcamera-apps, but is quite flexible and easy to use.

**Comment by davidplowman** [comment]
That PR has been merged now, and will become available in the next release. Alternatively, you can fetch the "next" branch and try it early. So I think I'll close this one now, and thanks again for the suggestion!
