### ISSUE TITLE
[OTHER] imx477 response curve

### ISSUE THREAD

**Issue by Bra1nsen** [raspberrypi/picamera2#368]
The camera response curve is a curve showing the relation between amount of incoming light and image pixel values of a camera sensor. (Opto-Electrical Transfer Function)

I was wondering if this function is linear or whether efforts have already been made to determine this curve for the imx477. (basically it should depend on the ad converter i guess)

kind regards

**Comment by davidplowman** [comment]
The default opto-electrical transfer function (OETF) that we use (we often call them just "gamma curves") is [here](https://github.com/raspberrypi/libcamera/blob/main/src/ipa/raspberrypi/data/imx477.json#L368). It's obviously non-linear.

In some of the experiments that you've been doing, I'm sure you'll recall that we changed this to a simple linear function, so that the pixel values correspond linearly to the light intensity.

**Comment by Bra1nsen** [comment]
Iam talking about the raw camera response curve. I remember the tuning file you provided david  (https://drive.google.com/file/d/1-olj82VusLTb6o68oQopO4ypYsS-iLGM/view)
--> for the radiometric characteristics 

you turned of 
i) the gamma correction
ii) image sharpeing
iii) color correction

What about the Auto White Balance?
it looks like its still turn on? It seems it depends on the lux value, which awb value is applied, is that correct?

**Comment by davidplowman** [comment]
I've never seen any information about the linearity of the sensor itself, but it certainly appears linear to the best of our ability to tell. I guess if someone wanted to understand this in greater detail they would have to start taking very careful measurements.

Yes, that tuning file turns off a number of things. The easiest way to turn off the AWB would be to set fixed colour gains (both to 1.0, presumably). I think maybe your Python scripts were doing that?

**Comment by Bra1nsen** [comment]
Maybe I could use the raw bayer numpy arrays we generated (exposureseries). They should be reasonable for determining the raw camera respone curve. Any thoughts on that?

Ahh yes we did `camera.set_controls({"ExposureTime": exp, "AnalogueGain": 1, "ColourGains": (1.0,1.0)})`

**Comment by davidplowman** [comment]
Yes, I think going right back to the raw Bayer arrays sounds like the right thing to do. You're absolutely guaranteed that no processing at all is being done to them.

**Comment by Bra1nsen** [comment]
Hey David, hope youre doing well.

I had the following idea:
-adding 4 raw bayer arrays up to get a 16 bit numpy array
-[converting it to 8 bit to save it as .tga ](https://www.youtube.com/watch?v=3vj3MTkBhWg&t=533s&ab_channel=DigitalSreeni)

I few questions come up. 
1. The raw binary output per pixel is 16bit, where we have 12bit dynamic range and 4bit "padding". What exactly do the remaining 4bits do?
2. What is buffer_count used for?
3. There is another problem with the format/ratio, somehow I can only do (760,2032,3) and not (1520,2032,3). Do you see why?
4. Is the script regarding my idea correct?

```
import sys
import numpy as np
import cv2
import imageio
from PIL import Image
from picamera2 import Picamera2
import imageio.v3 as iio
from skimage import exposure, img_as_ubyte


num_frames = 4

picam2 = Picamera2()
config = picam2.create_still_configuration(raw={"format": "SRGGB12", "size" : (2032, 1520)}, buffer_count=2)
picam2.configure(config)
picam2.set_controls({"ExposureTime": 240 // num_frames, "AnalogueGain": 1, "ColourGains": (1.0,1.0)})
images = []
picam2.start()

for i in range(num_frames):
    images.append(picam2.capture_array("raw"))

# Add arrays up
array16 = images.pop(0).astype(np.uint16)
for image in images:
    array16 += image

cv2.imwrite("array16.png", array16)
convert8bit_grey = img_as_ubyte(exposure.rescale_intensity(array16))
iio.imwrite('array16.tga', convert8bit_grey)

#create raw bayer array
rgb_array = np.zeros((760, 2032, 3), dtype=np.uint16)
rgb_array[:, :, 0] = array16[1::2, 1::2] # red
rgb_array[:, :, 1] = (array16[0::2, 1::2] + array16[1::2, 0::2]) / 2 # green
rgb_array[:, :, 2] = array16[0::2, 0::2] # blue

cv2.imwrite("rgb_array.png", rgb_array)
convert8bit_rgb = img_as_ubyte(exposure.rescale_intensity(rgb_array))
iio.imwrite('rgb_array.tga', convert8bit_rgb)

# Load images back and check errors are zero!
grey_check = cv2.imread("array16.png", cv2.IMREAD_ANYDEPTH | cv2.IMREAD_ANYCOLOR)
rgb_check = cv2.imread("rgb_array.png", cv2.IMREAD_ANYDEPTH | cv2.IMREAD_ANYCOLOR)
print(np.max(np.abs(array16 - grey_check)))
print(np.max(np.abs(rgb_array - rgb_check)))

picam2.stop()
picam2.close()
```

**Comment by davidplowman** [comment]
Hi, I've tried to write some answers inline!

> 1. The raw binary output per pixel is 16bit, where we have 12bit dynamic range and 4bit "padding". What exactly do the remaining 4bits do?

They don't do anything, it's just that computers prefer to store stuff in 16 (or 8, 32 or 64...) bits and not 12.

> 2. What is buffer_count used for?

This stops you dropping camera frames. If you only have 1 buffer, then it might not get recycled to the camera in time for the very next frame. That would mean you would drop a frame and only get the one after. If you have 2 buffers, then there will always be an available buffer for the camera to write to.

> 3. There is another problem with the format/ratio, somehow I can only do (760,2032,3) and not (1520,2032,3). Do you see why?

When you de-bayer the raw array like this you halve the width and the height. So actually 760 is correct. In fact the 2032 here is wrong (see below).

> 4. Is the script regarding my idea correct?

That depends! Check my comments below and decide if what you've done is OK for your application, I can't really say for sure.

> 
> ```
> import sys
> import numpy as np
> import cv2
> import imageio
> from PIL import Image
> from picamera2 import Picamera2
> import imageio.v3 as iio
> from skimage import exposure, img_as_ubyte
> 
> 
> num_frames = 4
> 
> picam2 = Picamera2()
> config = picam2.create_still_configuration(raw={"format": "SRGGB12", "size" : (2032, 1520)}, buffer_count=2)
> picam2.configure(config)
> picam2.set_controls({"ExposureTime": 240 // num_frames, "AnalogueGain": 1, "ColourGains": (1.0,1.0)})
> images = []
> picam2.start()
> 
> for i in range(num_frames):
>     images.append(picam2.capture_array("raw"))
> 
> # Add arrays up
> array16 = images.pop(0).astype(np.uint16)
> ```
I think here you want `view` and not `astype`. You need to "view" each pair of 8-bit numbers as a single 16-bit number, not convert each 8-bit number into a separate 16-bit number. So for example, if you have an array `[1, 1], dtype=uint8` you need to turn that into `[257], dtype=uint16` and not `[1, 1] dtype=uint16`. This is where you've doubled the width of your array.
>```
> for image in images:
>     array16 += image
>```
Here too I think you want `array16 += image.view(np.uint16)`.
>```
> 
> cv2.imwrite("array16.png", array16)
> convert8bit_grey = img_as_ubyte(exposure.rescale_intensity(array16))
>```
Just a warning here that you're applying a scaling that will vary from one image to another, so you can't really compare one file captured this way to another with a different exposure.
>```
> iio.imwrite('array16.tga', convert8bit_grey)
> 
> #create raw bayer array
> rgb_array = np.zeros((760, 2032, 3), dtype=np.uint16)
>```
The shape here will want to be `(760, 1016, 3)` once you've made the changes above.
>```
> rgb_array[:, :, 0] = array16[1::2, 1::2] # red
> rgb_array[:, :, 1] = (array16[0::2, 1::2] + array16[1::2, 0::2]) / 2 # green
> rgb_array[:, :, 2] = array16[0::2, 0::2] # blue
> 
> cv2.imwrite("rgb_array.png", rgb_array)
> convert8bit_rgb = img_as_ubyte(exposure.rescale_intensity(rgb_array))
> iio.imwrite('rgb_array.tga', convert8bit_rgb)
> 
> # Load images back and check errors are zero!
> grey_check = cv2.imread("array16.png", cv2.IMREAD_ANYDEPTH | cv2.IMREAD_ANYCOLOR)
> rgb_check = cv2.imread("rgb_array.png", cv2.IMREAD_ANYDEPTH | cv2.IMREAD_ANYCOLOR)
> print(np.max(np.abs(array16 - grey_check)))
> print(np.max(np.abs(rgb_array - rgb_check)))
> 
> picam2.stop()
> picam2.close()
> ```

Hope that makes sense!

**Comment by Bra1nsen** [comment]
Good Morning David, thanks alot.

1. if one goes for 4 frames, one shoudl get a 15 bit images right? (12+1+1+1)
So in order to use the full 16 bits, it would make sense to set 5 frames.
Would one take more than 5 frames e.g. 6 one would then have to choose uint32 right? or uint24?

2.   _> applying a scaling according to exposure profile will vary from one image to another_
good point, thanks for mentionted that. 

```
#Normalize then scale to 255 and convert to uint8 
Equals = (array16/(2^(num_frames+11)-1)) * 255
Equals = np.uint8(Equals)
iio.imwrite('equal.tga', Equals)
```
would you do it differently?

**Comment by davidplowman** [comment]
> 1. if one goes for 4 frames, one should get 15 bit images right? (12+1+1+1)
>    So in order to use the full 16 bits, it would make sense to set 5 frames.
>    Would one take more than 5 frames e.g. 6 one would then have to choose uint32 right? or uint24?

Not quite. You're just adding regular numbers so every time you _double_ the number of frames that adds 1 extra bit. So the number of extra bits is given by log2(num_frames). In Python you can calculate this efficiently with `num_frames.bit_length() - 1` when num_frames is a power of 2. In fact I would stick with powers of 2 for num_frames because everything will just get more complicated if you don't (you would need extra bits but then not use all the range they provide).

That means you'd have to add 16 frames together to give you 4 extra bits, which makes up 16 bits when you include the initial 12 in each pixel. If you went higher than 16 frames then you'd have to start using uint32 values. I'm quite sure uint24 won't exist - computers deal with powers of 2!

> 2. _> applying a scaling according to different exposure profiles will vary from one image to another_
>    good point, thanks for mentionted that.
> 
> ```
> #Normalize then scale to 255 and convert to uint8 
> Equals = (array16/(2^(num_frames+11)-1)) * 255
> Equals = np.uint8(Equals)
> iio.imwrite('equal.tga', Equals)
> ```
> 
> would you do it differently?

That looks fine, except that where you have `2^(num_frames+11)` you should have `2^(num_frames.bit_length()+11)` as per my earlier comment. And make sure that num_frames is always a power of 2!

**Comment by Bra1nsen** [comment]
Great explanation, got it!

`array16 = images.pop(0).view(np.uint16)`  why should one delete the first image array?

Moreover when we are capturing the raw bayer array, how do we be sure we get the 12 bits out?

```
#!/usr/bin/python3
from picamera2 import *

picam2 = Picamera2()
config = picam2.create_still_configuration(raw={"format": "SRGGB12", "size" : (2032, 1520)}, buffer_count=2)
picam2.configure(config)


picam2.set_controls({"ExposureTime": 60, "AnalogueGain": 1, "ColourGains": (1.0,1.0)})
picam2.start()
uno = picam2.capture_array("raw")

print(uno.dtype)
```

**`uint8`**

**Comment by davidplowman** [comment]
> `array16 = images.pop(0).view(np.uint16)` why should one delete the first image array?

Otherwise the loop would add the first image to itself again! You could have created an array of zeros of the correct size, and then not deleted the first image. But this way saves an image-add operation, not that it's a big deal.

> Moreover when we are capturing the raw bayer array, how do we be sure we get the 12 bits out?

After doing `picam2.configure(config)` it's always quite handy to have a look in `config["raw"]` to check what you're actually going to get. This should confirm that you're going to get 12-bit unpacked.

You can also check the captured raw array. The even numbered bytes will have values from 0 to 255. The odd numbered bytes give you the extra 4 bits, so you'll see values from 0 to 15.

> ```
> ...
> print(uno.dtype)
> ```
> 
> **`uint8`**

The raw array always comes back as bytes and you have to interpret it yourself. Because you asked for an unpacked format you can just use `np.view(uint16)` which is super-cheap as it doesn't even copy the data. Try this:
```
import numpy as np
bytes = np.array([1, 1], dtype=np.uint8)
words = bytes.view(np.uint16)  # words is [257]
bytes[0] = 2  # now words is [258] 
```
If you asked for _packed_ data, then `np.view` wouldn't be helpful and you'd have to unpack all the bits yourself and glue them back together which would be vastly more expensive. When you ask for raw images Picamera2 makes no attempt to interpret the camera data for you - you always get an array of bytes (uint8s).

**Comment by Bra1nsen** [comment]
ok figured it out. 

0000000100000001 can be either [1, 1] or 257 depending on view  ~ uint8 / uint16 dtype

so we have an array of uint8s which are essentielly uint12s but we use uint16s because of standardization purposes.

**Comment by Bra1nsen** [comment]
Hey David I tried the following:

```
#!/usr/bin/python3
import numpy as np
import cv2
import time
import imageio
import datetime
import imageio.v3 as iio
import matplotlib.image
import matplotlib.pyplot as plt
from PIL import Image
from skimage import exposure, img_as_ubyte
from datetime import timezone, timedelta, datetime
from time import sleep
from picamera2 import *
from numpy import asarray, save


dt = datetime.now(timezone.utc)
utc_time = dt.replace(tzinfo=timezone.utc)
utc_timestamp = int(utc_time.timestamp())
utc_timestamps = str(utc_timestamp)

t1= time.perf_counter()
os.chdir("/home/pi/High-Pricision_AD_HAT/python/testing4")

picam2 = Picamera2()
config = picam2.create_still_configuration(raw={"format": "SRGGB12", "size" : (2032, 1520)}, buffer_count=2)
picam2.configure(config)


picam2.set_controls({"ExposureTime": 60, "AnalogueGain": 1, "ColourGains": (1.0,1.0)})
picam2.start()
array = picam2.capture_array("raw")
picam2.stop()

hdr = array.view(np.uint16)

#Create raw bayer array image
rgb_array = np.zeros((760, 1016, 3), dtype=np.uint16)
rgb_array[:, :, 0] = hdr[1::2, 1::2] # red
rgb_array[:, :, 1] = (hdr[0::2, 1::2] + hdr[1::2, 0::2]) / 2 # green
rgb_array[:, :, 2] = hdr[0::2, 0::2] # blue

#Normalize then scale to 255 and convert to uint8 
equals_rgb = (rgb_array/(2^12-1)) * 255
equals_rgb = np.uint8(equals_rgb)
iio.imwrite(f'{utc_timestamp}_rgb.tga', equals_rgb)

#Normalize according to exposure profile
convert8bit_rgb = img_as_ubyte(exposure.rescale_intensity(rgb_array))
iio.imwrite(f'{utc_timestamp}_rgbexp.tga', convert8bit_rgb)
```

I was expecting such a image (bayer pattern)
![images](https://user-images.githubusercontent.com/58213050/198577088-bdecdb28-ab21-4b1d-8fe8-3a33674ff09d.jpg)

but i get a pattern like this:

![Screenshot 2022-10-28 133111](https://user-images.githubusercontent.com/58213050/198577435-fa693385-0241-4ea6-9d93-4be3f8d27953.png)

any idea why?

**Comment by davidplowman** [comment]
I think you're going to laugh. In Python, `^` is the bitwise-xor operator, not power. You need `**` instead!!

Also don't forget that you have demosaiced the image, so it won't have that green checkerboard-ish appearance of that first image.

**Comment by Bra1nsen** [comment]
changed to `**` but still no bayer pattern

but still

**Comment by davidplowman** [comment]
I'm not really sure what you're expecting to see. You won't see a "mosaic image" like the one you posted, because you have demosaiced it to a regular 3-channel RGB image. I would expect most of it to look dark, and where it isn't it will look very green (because the green channel is pretty much always to strongest in a raw image). Are you seeing something different?

**Comment by Bra1nsen** [comment]
so we create an empty array (760, 1016, 3)
```
rgb_array = np.zeros((760, 1016, 3), dtype=np.uint16)
```
then we catch from the raw bayer array the values            
```
rgb_array[:, :, 0] = hdr[1::2, 1::2] # red
```
Gb B
R  Gr     taking only the R's
```
rgb_array[:, :, 1] = (hdr[0::2, 1::2] + hdr[1::2, 0::2]) / 2 # green
```
Gb B
R  Gr     taking only the G's
```
rgb_array[:, :, 2] = hdr[0::2, 0::2] # blue
```
Gb B                                       0 B 0 B 0 B 
R  Gr     taking only the B's    0 0 0 0 0 0
                                               0 B 0 B 0 B

So I concluded we have 3 layer with only
 0 B 0 B 0 B            Gr 0 Gr 0 Gr 0 Gr           0 0 0 0 0 0 0
 0 0 0 0 0 0             0 Gb 0 Gb 0 Gb 0         R 0 R 0 R 0 R
 0 B 0 B 0 B            Gr 0 Gr 0 Gr 0 Gr          0 0 0 0 0 0 0

where is the demosaicing done?

or do we get 3 matrices like that:

B B B B B B         G G G G G G     R R R R R R
B B B B B B         G G G G G G     R R R R R R
B B B B B B         G G G G G G     R R R R R R

**Comment by Bra1nsen** [comment]
What needs to be changed to get the bayer pattern image David?

```
rgb_array[:, :, 0] = hdr[1::2, 1::2] # red
rgb_array[:, :, 1] = (hdr[0::2, 1::2] + hdr[1::2, 0::2]) / 2 # green
rgb_array[:, :, 2] = hdr[0::2, 0::2] # blue
```

**Comment by Bra1nsen** [comment]
I think i got it. Not really sure, can you check david?

```
bayer = np.zeros((2*760, 2*1016, 3), dtype=np.uint16)
bayer[::2, ::2, 2]=hdr[0::2, 0::2] #blue
bayer[1::2, ::2, 1]=hdr[0::2, 1::2] #green
bayer[::2, 1::2, 1]=hdr[1::2, 0::2] #green
bayer[1::2, 1::2, 0]=hdr[1::2, 1::2] #red
```
![bayer](https://user-images.githubusercontent.com/58213050/198827685-2a7dce7b-be8c-47f4-8646-fcc3a951b31e.png)

**Comment by Bra1nsen** [comment]
https://drive.google.com/drive/folders/1OhdrPW-tuikrWjRdvjtSEXOdeBfJXgAM?usp=sharing

**Comment by davidplowman** [comment]
> ```
> bayer = np.zeros((2*760, 2*1016, 3), dtype=np.uint16)
> bayer[::2, ::2, 2]=hdr[0::2, 0::2] #blue
> bayer[1::2, ::2, 1]=hdr[0::2, 1::2] #green
> bayer[::2, 1::2, 1]=hdr[1::2, 0::2] #green
> bayer[1::2, 1::2, 0]=hdr[1::2, 1::2] #red
> ```
Hi, it looks OK to me. The only comment I'd make is that you're swapping the two green samples over, i.e. you're filling `bayer[odd, even, 1]` from `hdr[even, odd]` and vice versa. So I would fix that, but otherwise looks good.

**Comment by Bra1nsen** [comment]
ah okay, corrected it.
```
bayer = np.zeros((2*760, 2*1016, 3), dtype=np.uint16)
bayer[::2, ::2, 2]=hdr[0::2, 0::2] #blue
bayer[1::2, ::2, 1]=hdr[1::2, 0::2] #green
bayer[::2, 1::2, 1]=hdr[0::2, 1::2] #green
bayer[1::2, 1::2, 0]=hdr[1::2, 1::2] #red
```

After looking at the IMX477 documentation, iam not quite sure about the color filter alignment.

![starting color pixel](https://user-images.githubusercontent.com/58213050/198985510-0d35af78-2d6a-4b64-aa1f-288198e0d7c8.png)

What would you say David? 
![Bayer-patterns-a-BGGR-b-GBRG-c-GRBG-and-d-RGGB](https://user-images.githubusercontent.com/58213050/198985741-71a4e9b4-2a1c-43eb-a949-391cfc3f7ee8.png)

**Comment by davidplowman** [comment]
You have to be quite careful interpreting this kind of information. You might sometimes find that a sensor doesn't read out the whole pixel array, and then the alignment where it starts (whether odd or even) may change the Bayer order. Similarly rotation is an issue. For example, most sensors support horizontal and vertical "flips", and this too often changes the Bayer order - after a "horizontal flip" RGGB would typically become GRBG.

All the official Raspberry Pi sensors are in this latter category, where flips change the Bayer order. For various reasons our sensors tend to be mounted "upside down" so we get the sensor to do a 180 rotation. On an imx477 this turns RGGB into BGGR and vice versa.

It's normally fairly obvious if the Bayer order is being misinterpreted. And you can always rely on the value of `config['raw']['format']` after you have called `picam2.configure`. This will always tell you the correct order for your raw stream.

**Comment by davidplowman** [comment]
I'm thinking we've answered the original question... probably best to file new issues as they come up (as you've done!) so I'll close this one. Thanks!
