### ISSUE TITLE
[HOW-TO] Capture continuous images from a stream

### ISSUE THREAD

**Issue by h-robotics** [raspberrypi/picamera2#370]
Hello,
I'm a beginner and I'm working on adding a text recognition feature for a robot I'm building using opencv and pytesseract. The tutorials I've found use the older picamera library and I've been looking for an alternative to the command picamera.capture_continuous and have not found it. Any ideas how to do this?

**Comment by davidplowman** [comment]
I don't think there's an API that is exactly the same, you would just put a `capture_array` or `capture_file` inside a loop. Here's one of our standard examples, showing one way to implement a continuous preview with text recognition: https://github.com/raspberrypi/picamera2/blob/main/examples/ocr.py

**Comment by davidplowman** [comment]
Hi, is there any other help you need with this question? If not, please do consider closing the issue, or I'll close it in a few days if nothing else comes up. Thanks!

**Comment by h-robotics** [comment]
Thank you, that helps! I will close the topic
