### ISSUE TITLE
Camera __init__ sequence did not complete 

### ISSUE THREAD

**Issue by Cande8a** [raspberrypi/picamera2#385]
I have the same problem as this: https://github.com/raspberrypi/picamera2/issues/300 , with the difference I have installed the picamera2 on a docker container, but I tried opening python from the terminal INSIDE docker and the picamera2 is imported and everything is ok, but when I run my whole project, where my python file for the camera is, I get this error. I made everything this issue (#300) explain, but it's still the same. I didn't installed picamera2 with pip, actually on my container I have it like it is recommended on github page.

![image](https://user-images.githubusercontent.com/98240227/198993822-0fb587f1-0779-4ea1-ac74-8193a0b8e52a.png)

This is the output for `uname -a` :
![image](https://user-images.githubusercontent.com/98240227/198994531-f16bc157-3645-4f62-b0a6-ba8e3a2cfa03.png)

The only difference I can see is that I don't have any output with `dmesg | grep ov5` , but this is the output from `cat /etc/os-release`
![image](https://user-images.githubusercontent.com/98240227/198993995-038d5783-26fd-48e6-ad84-effa20b4dacd.png)

I've been working through this issue many days and it's for my job, that's why I'm asking for help. Has anyone any idea about what to try? Thanks!!

_Originally posted by @Cande8a in https://github.com/raspberrypi/picamera2/issues/300#issuecomment-1296919939_

**Comment by chrisruk** [comment]
Hi, can you post the Dockerfile you used and I'll try and have a look.

It sounds like you installed in the Docker container, via apt?

**Comment by Cande8a** [comment]
Hi @chrisruk  thanks for your wuick response..
I can't send all the file for reproduction problems in my work, but this is what I've made regarding picamera2, I hope it would be enough to you.

```
RUN echo deb http://archive.raspberrypi.org/debian/ bullseye main | tee /etc/apt/sources.list.d/raspberrypi.list
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 7FA3303E
RUN apt-get update -y 
RUN apt-get upgrade -y

RUN apt install -y python3-picamera2 --no-install-recommends
```

Thanks in advance!

**Comment by Cande8a** [comment]
Sorry, I forgot this picture: output from `libcamera-hello`

![image](https://user-images.githubusercontent.com/98240227/198995739-2ed4e4b7-c3f6-4cc5-9b2f-76dac515031b.png)

**Comment by chrisruk** [comment]
Thanks, also what image are you using?

**Comment by Cande8a** [comment]
an image for arm64 on app, and redis on services. On my image for arm64 I call for all the installations for my requirements

**Comment by chrisruk** [comment]
I found a few things that where useful -

* https://forums.raspberrypi.com/viewtopic.php?t=325755 (the bottom post here)
* https://github.com/balena-io-experimental/libcamera-apps
* https://github.com/balena-io-library/base-images/blob/master/balena-base-images/amd64/ubuntu/focal/run/entry.sh

Used the following from the raspberry pi forum post -

```
docker run -it --rm --privileged -v /dev/:/dev/ --env UDEV=1 --device /dev:/dev --entrypoint /bin/bash <IMAGE>
```

I then did in the container

```
apt install udev
unshare --net /lib/systemd/systemd-udevd --daemon &> /dev/null
udevadm trigger &> /dev/null
udevadm control --reload
```

Then did

```
from picamera2 import Picamera2
picam2 = Picamera2()
picam2.start_and_capture_file("test.jpg")
```

There will be security implications of mapping all of /dev and using privileged.

**Comment by Cande8a** [comment]
Thank you so much @chrisruk !! I will read all of this and let you know if it's working. I'm also not so experienced with docker, but it's the way I need to do it.

**Comment by Cande8a** [comment]
Thanks @chrisruk !!
