### ISSUE TITLE
[HOW-TO] How to set timeout ? 

### ISSUE THREAD

**Issue by ozayr** [raspberrypi/picamera2#401]
how do I set the equivalent of the -t option in the libcamera cli tool

**Comment by davidplowman** [comment]
Hi, thanks for the question. Do you mean this kind of thing?
```
from picamera2 import Picamera2
import time

picam2 = Picamera2()
picam2.start(show_preview=True)
time.sleep(5)
```
which approximates the behaviour of `libcamera-hello`. Please get back to us if you're looking for something different. Thanks!

**Comment by davidplowman** [comment]
Hi, is there anything more we can help you with here? If not I'll consider closing this issue in a few days. Thanks!

**Comment by davidplowman** [comment]
I'll close this one now, if that's OK. But please open a new issue if anything else comes up. Thanks!
