### ISSUE TITLE
No named AwbModes

### ISSUE THREAD

**Issue by tvoverbeek** [raspberrypi/picamera2#43]
I would like to use the AWB mode names as defined in the libcamera documentation: auto, incandescent, tungsten, etc.
However only numeric values 0-7 are allowed now.
This is similar to #38 for exposure mode.

**Comment by davidplowman** [comment]
Hi, yes indeed, as I commented on that other issue, this clearly wants improving. It probably ought to be part of libcamera itself so we'll talk to them about that.
