### ISSUE TITLE
Picamera for windows

### ISSUE THREAD

**Issue by farhanalfin** [raspberrypi/picamera2#456]
I tried to use Picamera 2 with a Windows as OS for raspberry pi 4, but give me this error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      This module only works on linux

is there any solution for this situation?

**Comment by davidplowman** [comment]
I'm sorry, but we don't support Picamera2 on any form of Windows OS. You would probably need to contact the developer/maintainer of the Windows port for Raspberry Pi.  Sorry not to be more help.

**Comment by farhanalfin** [comment]
Thank you for your reply
