### ISSUE TITLE
[OTHER - Documentation]  Latest issue of picamera2-manual

### ISSUE THREAD

**Issue by sandyol55** [raspberrypi/picamera2#464]
On re-reading the latest issue - after recently 'jumping the gun' to raise an issue that was clearly covered by advice present therein  :-)  
came across these potential improvements.

References to no support for USB cameras in opening para in Chapter 1 overtaken by 4.4?

P15 Code snippet in 4.1 has typo in import statement (Picamera/Picamera2)

P17 preview_config code snippet in 4.2.1.1   should be (transform=Transform(hflip=True))
No need for libcamera.Transform as already specifically imported?

**Comment by davidplowman** [comment]
Thanks for spotting those! I'm just updating the manual for the next release and so I should be able to get these straight in.
