### ISSUE TITLE
[BUG] sensor modes.

### ISSUE THREAD

**Issue by pbaetens** [raspberrypi/picamera2#485]
```
from picamera2 import Picamera2
picam2=Picamera2()
print(picam2.sensor_modes)

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.9/site-packages/picamera2/picamera2.py", line 341, in sensor_modes
    cam_mode["fps"] = round(1e6 / min(frameDurationLimits), 2)
TypeError: '<' not supported between instances of 'NoneType' and 'int'

this piece of code fails.
content of frameDurationLimits is:
[2510, 213406, None]
probably the third element should not be there?

**Comment by pbaetens** [comment]
side note: using self-compiled libcamera, self-compiled picamera2, self-written camera driver for custom CMOS image sensor.
most features work fine though.

**Comment by davidplowman** [comment]
We did see this error some time ago when mainline libcamera changed.

Please check that you are obtaining the latest version of libcamera from https://github.com/raspberrypi/libcamera and the latest version of Picamera2.

**Comment by pbaetens** [comment]
thanks. The official raspberry pi/libcamera repo seems to work better!

**Comment by davidplowman** [comment]
In general libcamera mainline can move on and break Picamera2, so our fork always contains the most recent version that we've confirmed works. As necessary we may sometimes update Picamera2 to work with the latest libcamera and then we can move our fork of libcamera forward again.
