### ISSUE TITLE
[BUG] DUAL CAMERA on CM4

### ISSUE THREAD

**Issue by pbaetens** [raspberrypi/picamera2#486]
it is currently not possible to create 2 preview windows.

what would be needed to implement this?

using libcamera-hello, I can have both cameras operating at the same time.
in picamera2, I did not manage so far.  (dual jpg capture works, dual preview does not..)

any workarounds?

**Comment by davidplowman** [comment]
Hi, dual preview windows should work, for example https://github.com/raspberrypi/picamera2/blob/main/tests/multicamera.py

If you have code that doesn't work, please post a small test case that demonstrates the problem - it's a bit hard to know how to help you otherwise.

**Comment by pbaetens** [comment]
indeed- issue for me was again not using the raspberrypi/libcamera repo. Issue solved.
