### ISSUE TITLE
[BUG] FfmpegOutput class : audio_samplerate parameter not used (typo)

### ISSUE THREAD

**Issue by Kinchul** [raspberrypi/picamera2#513]
In the FfmpegOutput class, implemented in _picamera2/picamera2/outputs/ffmpegoutput.py_, the audio_samplerate paramter is not used in the start() method due to a typo on line 62, where the bitrate variable is use instead:

`'-sample_rate', str(self.audio_bitrate),`

It is probably a typo, the correct line should be:

`'-sample_rate', str(self.audio_samplerate),`

**Comment by davidplowman** [comment]
Oops, thanks for pointing that out. I'll patch that up right away!

**Comment by davidplowman** [comment]
That's been merged onto our "next" branch now so it'll be in the next release. Thanks again.
