### ISSUE TITLE
Install the package

### ISSUE THREAD

**Issue by chrishanfernando** [raspberrypi/picamera2#522]
I'm trying to run a python script in my Rasbperry pi that imports the package picamera2. Specifically using `from picamera2 import Picamera2,Preview
`
However, I'm getting this error: `ImportError: No module named 'picamera2'`

Struggling to get it installed. Why can't this package be found?

I've tried to install the package by doing an update and installing the package 

```
sudo apt update
sudo apt full-upgrade
sudo apt install -y python3-picamera2
```
But running the last line returns the error: `Unable to locate package python3-picamera2`

I've also tried `pip install picamera2` but that returns `No matching distribution found for picamera2`

Info:

- Rasbperry pi 3 Model B
- OS: Raspbian GNU/Linux 9 (stretch)

**Comment by davidplowman** [comment]
Hi, it seems like you're not managing to upgrade to the latest OS release which should be Bullseye. libcamera and Picamera2 won't work on anything older than that. If possible I'd recommend starting with a fresh copy of our latest OS and then letting it perform all its updates when you first boot it.
