### ISSUE TITLE
Capture Consistent Images [HOW-TO]

### ISSUE THREAD

**Issue by qmcgrath** [raspberrypi/picamera2#525]
Hello,
My end goal is to capture consistent images for medical purposes. 

Im using a 64 MP arducam camera on an rpi4. I will be changing the exposure time for every image captured (ie first image at 3000, then one at 5000, with ideally everything kept consistent between them). 

I am writing to ensure I am capturing consistent images as outlined for picamera 1 with mmal, as thats pretty well documented online. 
https://gist.github.com/rwb27/a23808e9f4008b48de95692a38ddaa08

If via controls I:
turn off AEenable and Awenable and Noise reduction 
set the exposure and Analogue gain (1.0) to specific values 
"picam2.set_controls({"ExposureTime": expTimes[0], "AeEnable":0,"AwbEnable":0,"AfMode":1,"AnalogueGain":1.0,"Saturation":0.0, "NoiseReductionMode":0,}); " 

Do I have to worry about any digital gain doing something weird internally if Im all updated? as that cant be accessed? per this discussion that makes it seems like this is a recent fix https://github.com/raspberrypi/picamera2/issues/425

Btw, I am using yuv420 as I only care about greyscale intensity. 

Thank you 

PS. I first tried to use raw signals, so I dont have to deal with anything but exposure time and analogue gain. I am following example stack_raw.py. However, it fails to start/allocate memory if I configure with a still_configuration (as done in the example). I assume this is just because 64 mp raw files must be to big. If you have any suggestions for how to make raw files work thats great also!

**Comment by davidplowman** [comment]
Hi, thanks for the question. It should be enough to specify exposure time and analogue gain explicitly as you are doing (that will automatically turn off the AEC/AGC).

You may also want to set explicit colour gains. You could check what the "correct" values are and use those, though it's probably not very critical if you only use the greyscale channel.

I doubt the disabling noise reduction will have much effect. The noise in any image changes anyway, but obviously you're free to disable it if you're happy to get some extra detail at the cost of noise.

Finally, there are a couple of algorithms running that have an adaptive behaviour, but you can disable those in the camera tuning file. Search for the "n_iter" parameter and set that to zero, also find "ce_enable" and set that to zero as well.
