### ISSUE TITLE
[SUGGESTION] picamera2 preview in pygame

### ISSUE THREAD

**Issue by pascalsoler** [raspberrypi/picamera2#527]
Hello everybody.
I am using pi v2 cameras in a photobooth type système using pygame and a python application, to preview video from pi cameras and to take pictures.
the preview is done with picamera.start_preview() instructions.

The video is then directly played in pygame.

I replaced my cameras with the PiCamera v3 12Mb module. The cameras work fine with libcamera and picamera2. OS and depency are uptodate.
BUT the preview in pygame doesnt work.
I tested all features picamera2.start_previe(xxxxxx), no video streams appears in pygame. Black screen.

Does this feature exist today?  If yes wich syntax to use?
is it planned? at what due date

Thanks a lot
Pascal

**Comment by davidplowman** [comment]
Hi, I'm afraid I don't really know enough about pygame to comment. Do I understand from your report that the v2 camera works, but the v3 does not? I can't really give you any explanation for that, unless perhaps the image from the v3 camera is too big? If you had a (_very_ simple!) test case that works with the v2 but not the v3 that might help. Thanks!

**Comment by pascalsoler** [comment]
Hi!
Here find my simple code to test pygame + picamera2 + cam module v3
thanks for your answer. I tried to modify image size in v3cam but pb is the same.

tested on Raspberry Pi 3B Bulleyes updated from today
cam v2 is working fine with raspivid -f (legacy cam is ENABLED in raspi-config)
cam v3 is working fine with libcamera-hello (legacy cam is DISABLED, glamor is enabled, gpu mem=256m, opengl kms selected)

NOTE camv2 can't be used with picamera2 and camv3 can't be used with picamera. ON/OFF lrgacy cam must be switched if you want use camv2 or camv3 hardware

TEST1: Using camv2 / legacy cam enabled, this code add a video layer to the pygame window
and preview from cam is displayed in pygame window.
We use picam library

===========================================================
#!/usr/bin/python3
# -*- coding: utf-8 -*

import picamera 
import os
import pygame
import sys
import time

pygame.init()
res = (1024,800)
#if you want a separate pygame window
#screen = pygame.display.set_mode(res)

#if you want a full screen pygame window 
screen = pygame.display.set_mode((0,0),pygame.FULLSCREEN)


camera=picamera.PiCamera()
camera.resolution= (800,600)

camera.start_preview() #pygame screen is black, no preview, no errors

time.sleep(10)

camera.stop_preview()
camera.close()

===============================================================
TEST2: Using camv3 / legacy cam DISABLED, read comments in the code for results
when you want to preview video strem on  pygame window

We use picam2 library
===================================================

#!/usr/bin/python3
# -*- coding: utf-8 -*

from picamera2 import Picamera2 , Preview
import os
import pygame
import sys
import time

pygame.init()
res = (1024,800)
#if you want a separate pygame window
#screen = pygame.display.set_mode(res)

#if you want a full screen pygame window 
screen = pygame.display.set_mode((0,0),pygame.FULLSCREEN)

camera=Picamera2()

#trying to modify image size
camera.preview_configuration.enable_lores()
camera.preview_configuration.lores.size=(800,600)
camera.preview_configuration.main.size = (800,600)
camera.configure("preview")
camera.controls.ExposureTime = 10000

#camera.start(show_preview=True) 	#this show preview in the separate QTGL Window, pygame screen is black
#camera.start_preview(Preview.NULL) #pygame screen is black, no preview, no errors
#camera.start_preview(Preview.DRM)	#pygame screen is black, no preview, no errors
#camera.start_preview(Preview.QT)	#pygame screen is black, separate QTPreview Window opens but is black
#camera.start_preview(Preview.QTGL)	#pygame screen is black, separate QTGLPreview Window opens but is grey

camera.start_preview() #pygame screen is black, no preview, no errors

time.sleep(10)

camera.stop_preview()
camera.close()

======================================================

**Comment by davidplowman** [comment]
Hi again, thanks for posting some example code. I've tried some of it out but the only thing I can see that's wrong is that it often calls `start_preview` but not `start`. Calling `start_preview` starts the preview window event loop, but it does not start the camera - so you will not see any frames. Someone has to call `start`.

As far as I can tell, if I start both the preview and the camera, everything works as expected for both v2 and v3 cameras. It's true that there is nothing in the pygame window, but given that nothing is being rendered there I wouldn't expect it. However, the following works nicely:
```
from picamera2 import Picamera2
import pygame

pygame.init()
res = (1024,768)
screen = pygame.display.set_mode(res)

camera = Picamera2()
camera.preview_configuration.main.size = res
camera.preview_configuration.main.format = 'BGR888'
camera.configure("preview")
camera.start()

while True:
    array = camera.capture_array()
    img = pygame.image.frombuffer(array.data, res, 'RGB')
    screen.blit(img, (0, 0))
    pygame.display.update()
```
Does any of that help?

**Comment by eat-sleep-code** [comment]
@davidplowman, using your code as a guide, how would I preview at that res, but do a capture at full res.

For example...

```
i = 0
while True:
    i = i+1
    array = camera.capture_array()
    img = pygame.image.frombuffer(array.data, res, 'RGB')
    screen.blit(img, (0, 0))
    pygame.display.update()
    # some logic to detect that I want to take a pic
    camera.capture_file("test" + str(i) + ".png") #works, but seems to be at preview size?   
 ```

**Comment by pascalsoler** [comment]
Hi 
effectivly the code of David capture still image at the same resolution 
find below a little modification to capture still image at a different resolution


from picamera2 import Picamera2
import pygame

pygame.init()
res = (1024,768)
screen = pygame.display.set_mode(res)

camera = Picamera2()
camera.preview_configuration.main.size = res
camera.preview_configuration.main.format = 'BGR888'
camera.configure("preview")

#####################
# here configure still capture
capture_config = camera.create_still_configuration()
camera.still_configuration.main.size = (2500,2500)
#####################

camera.start()

while True:
##################################
# depress a key 6> capture image
#################################
    events=pygame.event.get()
    for e in events:
        if (e.type == pygame.KEYDOWN and e.key == pygame.K_a):
            print("capture image")
            camera.switch_mode_and_capture_file(capture_config, "image.jpg")
            print("display image")
            img=pygame.image.load("aaaaa.jpg").convert()
            rect=img.get_rect()
            screen.blit(img, rect)
            pygame.display.update()
            print("display image 5s")
            time.sleep(5)

    array = camera.capture_array()
    img = pygame.image.frombuffer(array.data, res, 'RGB')
    screen.blit(img, (0, 0))
    pygame.display.update()

**Comment by eat-sleep-code** [comment]
@pascalsoler  Thanks, I took your code and adapted it just a bit but I am getting an error when I press the key to capture.

```
python3 test.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
[0:00:46.312108119] [1207]  INFO Camera camera_manager.cpp:299 libcamera v0.0.2+55-5df5b72c
[0:00:46.353333397] [1214]  INFO RPI raspberrypi.cpp:1425 Registered camera /base/soc/i2c0mux/i2c@1/imx477@1a to Unicam device /dev/media3 and ISP device /dev/media2
[0:00:46.357623138] [1207]  INFO Camera camera.cpp:1026 configuring streams: (0) 1024x768-BGR888
[0:00:46.357948082] [1214]  INFO RPI raspberrypi.cpp:805 Sensor: /base/soc/i2c0mux/i2c@1/imx477@1a - Selected sensor format: 2028x1520-SBGGR12_1X12 - Selected unicam format: 2028x1520-pBCC
Capturing frame...
[0:00:48.819702618] [1218]  INFO Camera camera.cpp:1026 configuring streams: (0) 4056x3040-BGR888
[0:00:48.823342914] [1214]  INFO RPI raspberrypi.cpp:805 Sensor: /base/soc/i2c0mux/i2c@1/imx477@1a - Selected sensor format: 4056x3040-SBGGR12_1X12 - Selected unicam format: 4056x3040-pBCC
[0:00:48.827105636] [1214] ERROR V4L2 v4l2_videodevice.cpp:1241 /dev/video14[25:cap]: Unable to request 1 buffers: Cannot allocate memory
Failed to allocate buffers.
Traceback (most recent call last):
  File "/home/pi/camera/test.py", line 37, in <module>
    camera.switch_mode_and_capture_file(configStill, filename)
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 1232, in switch_mode_and_capture_file
    return self.dispatch_functions(functions, wait, signal_function)
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 1163, in dispatch_functions
    return job.get_result() if wait else job
  File "/usr/lib/python3/dist-packages/picamera2/job.py", line 77, in get_result
    return self._future.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 440, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3/dist-packages/picamera2/job.py", line 47, in execute
    done, result = self._functions[0]()
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 1208, in switch_mode_
    self.configure_(camera_config)
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 956, in configure_
    raise RuntimeError("Failed to allocate buffers.")
RuntimeError: Failed to allocate buffers.
```

This is my code...

```python
from picamera2 import Picamera2
from libcamera import ColorSpace
import pygame
import time

pygame.init()
appWidth = 1024
appHeight = 768

screen = pygame.display.set_mode((appWidth, appHeight))

camera = Picamera2()

# === Create Configurations ====================================================

configPreview = camera.create_preview_configuration()
camera.preview_configuration.main.size = (appWidth, appHeight)
camera.preview_configuration.main.format = 'BGR888'
camera.configure('preview')

# ------------------------------------------------------------------------------

configStill = camera.create_still_configuration()
camera.still_configuration.enable_raw()
camera.still_configuration.main.size = camera.sensor_resolution
camera.still_configuration.buffer_count = 2
camera.still_configuration.colour_space = ColorSpace.Sycc()

camera.start()

while True:
    events=pygame.event.get()
    for e in events:
        if (e.type == pygame.KEYDOWN and e.key == pygame.K_SPACE):
            filename = 'image.jpg'
            print('Capturing frame...')
            camera.switch_mode_and_capture_file(configStill, filename)
            
            print('Displaying the captured frame for 5 seconds...')
            capturedFrame = pygame.image.load(filename).convert()
            capturedFrameRectangle = capturedFrame.get_rect()
            screen.blit(capturedFrame, capturedFrameRectangle)
            pygame.display.update()
            time.sleep(5)

    array = camera.capture_array()
    previewFrame = pygame.image.frombuffer(array.data, (appWidth, appHeight), 'RGB')
    screen.blit(previewFrame, (0, 0))
    pygame.display.update()
```

This is occurring on a Pi 4 8GB.  It occurs with the GPU split set at 64MB or 256MB.

**Comment by pascalsoler** [comment]
@eat-sleep-code Hi!
I just try to copy paste your code on my:
PI3 + cam v3  (legacy cam is DISABLED, glamor is enabled, gpu mem=256m, opengl kms selected)

It's working fine!

**Comment by pascalsoler** [comment]
@davidplowman 
Hi David!
I have tested several code, to Preview video and Capture Image. (Code QT5 in this GitHub (app_image_capture.py), and code Pygame in this Discussion)
Video Preview an Capture Image are working fine BUT I don't UNDERSTAND the signification of the term RESOLUTION.

Native Image are 4608 x 2592 pixel
if I use 1/3 aspect ratio for preview (1536x864). Normally, I should get the same image (Vue) as at full resolution, but with less pixels: 1536x864.
But the preview actually displays a video of 1536x864 (I think) which is a cropped view of the full resolution image. But the worst thing is that, one could imagine that this cropped image is centered in relation to the full resolution image and this is not the case. there is a strong discrepancy.

My question is:
How to get the same image in preview and capture? for example:
preview in 1536x1024 and capture in 4608x2592 (same view, more pixels, more resolution) or preview in 1024x800 and capture in 2048x1600?
Preview and Capture width and height, can be configured separately, but they do not display the same view.

Thanks
Pascal

**Comment by davidplowman** [comment]
Hi, a couple of things you might need to know.

1. Don't increase gpumem in the config.txt file. The camera system doesn't use it and the memory will probably be wasted. Instead you probably need to increase the amount of CMA. With an 8GB Pi you could probably go all the way to 512MB. Please see section 8.3 of [the manual](https://datasheets.raspberrypi.com/camera/picamera2-manual.pdf).

2. Secondly, you can choose particular camera modes to give you a specific field of view.  Try adding
```
camera.preview_configuration.raw.size = (2304, 1296)
```
here, specifying the "raw" camera mode resolution  will force the use of a full field of view camera mode. (I notice you create a `previewConfig` but then don't use it. Actually this is correct, if you're using the `preview_configuration` structure then don't use `create_preview_configuration`.)

Finally, if you want to use the structure syntax for configuration, then don't create a separate configuration using `create_still_configuration`. Rather like you did with the preview mode, use
```
camera.switch_mode_and_capture_file('still', filename)
```

A couple of extra tips: you probably don't need a `buffer_count` of 2 if you're doing a single still capture. 1 should do (and ease pressure in the CMA memory area). It may run quicker if you capture a request as that will both save a JPEG and give you the image that was saved, something like:
```
request = camera.switch_mode_and_capture_request('still')
request.save('main', filename)
array = request.make_array('name')
request.release()
# Now display array for 5 seconds...
```

**Comment by eat-sleep-code** [comment]
Thanks!   I remembered I had legacy camera support enabled.   After disabling legacy camera support and making the CMA adjustment, it works fine!   I will do the other adjustments saving optimizations in my final program.   Thank you both for the guidance.

**Comment by eat-sleep-code** [comment]
@davidplowman Well, I ran into one hiccup.   I went into `/boot/config.txt` and found this one line `#dtaoverlay=vc4-kms-v3d`.   I uncommented it and added `cma-512` to the end.  I rebooted and when I VNC'd into the machine the camera worked great.

However... later I realized that the LCD connected to the PI no longer worked.   I went back and commented that line out and the display works again.

I found this line in the file `dtoverlay=mhs35:rotate=90` for the drivers for the display.    I tried adding `,cma=512` but it seemed to have no affect on the setup.   The display works, but I get the cannot allocate buffer error again.

Here is the full `/boot/config.txt` as of right this moment:

```sh
# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
#hdmi_safe=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
#hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
#config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
#arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Uncomment this to enable infrared communication.
#dtoverlay=gpio-ir,gpio_pin=17
#dtoverlay=gpio-ir-tx,gpio_pin=18

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

# Automatically load overlays for detected cameras
camera_auto_detect=1

# Automatically load overlays for detected DSI displays
display_auto_detect=1

# Enable DRM VC4 V3D driver
#dtoverlay=vc4-kms-v3d,cma-512
max_framebuffers=2

# Run in 64-bit mode
arm_64bit=1

# Disable compensation for displays with overscan
disable_overscan=1

[cm4]
# Enable host mode on the 2711 built-in XHCI USB controller.
# This line should be removed if the legacy DWC2 controller is required
# (e.g. for USB device mode) or if USB support is not required.
otg_mode=1

[all]

[pi4]
# Run as fast as firmware / board allows
arm_boost=1

[all]
hdmi_force_hotplug=1
dtparam=i2c_arm=on
dtparam=spi=on
enable_uart=1
dtoverlay=mhs35:rotate=90,cma=512
hdmi_group=2
hdmi_mode=1
hdmi_mode=16
hdmi_cvt 960 640 120 0 0 0
hdmi_drive=2
gpu_mem=256
```

I believe this is the LCD that is connected to it: http://www.lcdwiki.com/MHS-3.5inch_RPi_Display

**Comment by davidplowman** [comment]
@6by9 Could you maybe comment on the correct solution for using an LCD here? Thanks!

**Comment by 6by9** [comment]
It's an ILI9486 SPI driven screen.
```dtoverlay=mhs35``` won't work on a standard Raspberry Pi OS system as they haven't bothered to request their overlay to be merged. Support should really come from your screen vendor due to this. (Things that have been accepted we will take a moderate level of support over)

It's relying on the old fbcp driver to copy pixel data from the HDMI output to a secondary framebuffer using dispmanx. DispmanX is incompatible with DRM.

Potentially you could tell pygame to render to /dev/fb1 instead of /dev/fb0, but don't ask me how (Google [suggests](https://stackoverflow.com/questions/54778105/python-pygame-fails-to-output-to-dev-fb1-on-a-raspberry-pi-tft-screen) ```export SDL_FBDEV=/dev/fb1```, or some other options)

Otherwise you need a DRM driver for your display. There is a DRM [ILI9486 driver in the kernel](https://github.com/raspberrypi/linux/blob/rpi-5.15.y/drivers/gpu/drm/tiny/ili9486.c), but no currently not built and it doesn't have an overlay to load and configure it. 
It looks like I did do some work on the conversion from https://forums.raspberrypi.com/viewtopic.php?t=345063, and I've now pushed it to https://github.com/6by9/linux/tree/rpi-5.15.y-ili9486. I didn't get it fully working with X as I had previously with an ILI9341 screen which is why I hadn't PRed it, but it's not a priority for me.

**Comment by 6by9** [comment]
The easier option is probably to switch to an HDMI, DPI, or DSI screen. All of those can be driven directly from the standard display pipeline.

DPI screens such as the Pimoroni HyperPixel4 panels ([800x480](https://shop.pimoroni.com/products/hyperpixel-4?variant=12569485443155) or [720x720](https://shop.pimoroni.com/products/hyperpixel-4-square?variant=30138251444307)) do take up a fair number of the available GPIOs. They are also generally only 18bit RGB to avoid stealing all the GPIOs. However both of those (and the Hyperpixel2Round) all have overlays in the standard Pi kernel.

There are a few DSI screens around, which largely clone the Pi 7" DSI panel at 800x480. Waveshare make a number. There are a few other 3rd party DSI screens available, but do check on the driver arrangements before buying.

HDMI is the easiest option. You'll find a fair number if you search for eg "5" HDMI touchscreen" on Amazon or similar. You'll get a range of resolution options, and generally should all be compatible (do stick with using vc4-kms-v3d as the firmware doesn't handle the weird resolutions that some of these use particularly well).

**Comment by davidplowman** [comment]
Is there anything else to investigate here? If not I'll consider closing it in a short while. Thanks!

**Comment by pascalsoler** [comment]
It's okay for me. Manu Thanks David. Regards.
