### ISSUE TITLE
[HOW-TO] use AeConstraintMode Custom

### ISSUE THREAD

**Issue by RolandasRazma** [raspberrypi/picamera2#537]
Was reading documentation and noticed AeConstraintMode have "Custom" but can't see anywhere how to us it.
Should I just use tuning file and add "custom" to "constraint_modes" or is there some API for it?

**Comment by davidplowman** [comment]
Yes, setting the libcamera control to `Custom` should switch over to the one named `"custom"` (if available) in the tuning file.
