### ISSUE TITLE
MJPEG Encode grayscale

### ISSUE THREAD

**Issue by tf4ong** [raspberrypi/picamera2#550]
I was wondering if there is a way to have the MJPEG encoder only encode grayscale images during a stream/video recording?

**Comment by davidplowman** [comment]
Hi, thanks for the question. The easiest thing would be just to set the whole camera system to give you greyscale images. To do this, just before or after starting the camera use
```
picam2.set_controls({"Saturation": 0.0})
```
It's more complicated if you wanted to receive full colour images from the camera but then only encode greyscale, I think you'd probably have to change the pixel colour values, which would cost CPU.

**Comment by davidplowman** [comment]
Hi, just wondering if there's anything else for us to investigate here? Thanks!

**Comment by davidplowman** [comment]
I'll close this one for the time being. Please open another issue if there's anything else. Thanks!
