### ISSUE TITLE
[HOW-TO] Get current focus distance

### ISSUE THREAD

**Issue by azsde** [raspberrypi/picamera2#571]
Hello,

I would like to determine the focus distance of the camera once the autofocus has finished, is there a way to retrieve this info ?

**Comment by davidplowman** [comment]
You should be able to to query the lens position, for example
```
lens_position = picam2.capture_metadata()['LensPosition']
```
The units are dioptres so take its reciprocal to get metres (obviously watch out for zero meaning "infinity").
