### ISSUE TITLE
[HOW-TO] VBR encoding

### ISSUE THREAD

**Issue by arkanoid87** [raspberrypi/picamera2#577]
With legacy camera stack was possible to encode with variable bit-stream compression (VBR) by setting bitrate to zero.
It was also possible to use `quantisation-parameter` to control the amount of variable compression:

`-qp, --qp	: Quantisation parameter. Use approximately 10-40. Default 0 (off)`

The raspivid and other legacy wrappers still handles this feature nicely
https://gstreamer.freedesktop.org/documentation/rpicamsrc/index.html?gi-language=c#rpicamsrc:bitrate
https://gstreamer.freedesktop.org/documentation/rpicamsrc/index.html?gi-language=c#rpicamsrc:quantisation-parameter

But I can't find this feature available when using Picamera2 interface, so I'm stuck with legacy.

I've found [this forum post on the topic ](https://forums.raspberrypi.com/viewtopic.php?p=2081053#p2081053) but it's not clear if VBR can be enabled or not on the lower levels of the new libcamera stack.

**Comment by davidplowman** [comment]
Hi, does [this](https://github.com/raspberrypi/picamera2/pull/579) look like what you need in Picamera2? Thanks!

**Comment by davidplowman** [comment]
That will only set the quantiser when you start the encoder. I think the same is true of the bitrate, that is, you can't change it once it's going (other than by doing the necessary ioctls yourself).

**Comment by davidplowman** [comment]
Great, glad that you found it. We're going to be doing an updated release very soon, hopefully, so I'll make sure we've got up-to-date versions of everything in place.

**Comment by davidplowman** [comment]
Still checking on a couple of things so no worries, I'll close it shortly. I'm really hoping to get an updated release out soon!

**Comment by davidplowman** [comment]
Closing because this feature should be available in release 0.3.9.
