### ISSUE TITLE
[HOW-TO]How to solve camera color deviation

### ISSUE THREAD

**Issue by yingliuzhizhuzed** [raspberrypi/picamera2#584]
**Please only ask one question per issue!**
In fact, my light source is a green laser light source, and I added a green light filter in front of my camera. Then the problem comes. The color in the image I get is purple, which is not normal for me. I don't know much about the color space of the camera.
**Describe what it is that you want to accomplish**
Now the picture is like this：
![image](https://user-images.githubusercontent.com/113871035/220871465-59a06f8b-999e-4680-a9d1-ac2adee7669f.png)
I wish my picture like this（by my phone）
![image](https://user-images.githubusercontent.com/113871035/220872227-effe4603-5b2b-495d-87d8-e13887dec8d2.png)

**Comment by davidplowman** [comment]
The AWB algorithm is calibrated for the kinds of lights that we find in typical indoor and outdoor environments. As your light source sounds different, you probably need to set the colour gains manually, for example
```
picam2.set_controls({'ColourGains': (1.5, 1.5)})
```
The first of the two numbers is the red gain, and the second is the blue gain. You would need to adjust them to get the result that you want. Hope that helps!

**Comment by yingliuzhizhuzed** [comment]
Thank you，i will try it.In addition, the camera I am using is not the official camera. I am considering whether to use the official V3 camera. Maybe his performance will be better.
