### ISSUE TITLE
[HOW-TO] flickering lights / Hz change?

### ISSUE THREAD

**Issue by RolandasRazma** [raspberrypi/picamera2#609]
Some of my videos are flickering when there is an external light bulb. There is usually a power line frequency change on USB cameras to work around that. Is there anything like that on picamera2?

**Comment by davidplowman** [comment]
There was some discussion of this on the libcamera mailing list a little while ago, but there haven't been any updates.  The AGC/AEC on the Pi is able to avoid 50/60Hz flicker by using multiples of the lighting period, but there is no API to enable it. Sorry not to have better news on that.

**Comment by RolandasRazma** [comment]
I see, thanks for the answer.

**Comment by RolandasRazma** [comment]
looks like it was implemented in libcamera-apps https://github.com/raspberrypi//pull/544/files

**Comment by davidplowman** [comment]
Yes, once we pick up an updated version of libcamera these controls will just appear automagically in picamera2 as camera controls.
