### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get' in request.py

### ISSUE THREAD

**Issue by Petros626** [raspberrypi/picamera2#612]
Following short example leads me (after 2 pressing 'p') to error below.

```python
.
# imports and def getkey() above...

cam = Picamera2()
cam.start_preview(Preview.QTGL)
cam.start()
request = cam.capture_request()
savepath = "/home/pk/camera/image/"
imgname = "picture"

try:
    while 1:
        key = getkey()
        if key == 'p':
            request.save("main", savepath + imgname, format="png")
            print("Picture taken and saved")
            request.release() # <-- problem seems here
        elif key == 'q':
            print("Closing camera...")
            break
finally:
    cam.stop_preview()
    cam.stop()
    cam.close()
```
After executing the script I get the following message, but with paste `request.release` for example before `finally:`, it seems not to be a problem.
![image](https://user-images.githubusercontent.com/62354721/224026194-d3d6a7cd-49da-4069-9871-93c4795fd4ad.png)

**Comment by davidplowman** [comment]
Hi, it may just be that you need to move the line `request = cam.capture_request()` to just before `request.save(...)`. You need to capture a request every time you want a new image. Once you release a request, you can't use it again. Does that explain it?

**Comment by Petros626** [comment]
I understand, thanks.
