### ISSUE TITLE
Imaging through PyQT fails on switch mode

### ISSUE THREAD

**Issue by Naderschah** [raspberrypi/picamera2#620]
**Please only report one bug per issue!**

**Describe the bug**

When utilizing any of the QT based scripts in example or my own, the camera gets stuck on switch_mode. 
This only occurs when one has first set a config mode (usually for preview, but the same is the case if one starts with still and switches to preview) and then attempts to switch for imaging. 
Within switch no Debug output is given.

**To Reproduce**
Steps to reproduce the behaviour. Wherever possible, please include a small self-contained Python script that shows the bug.

Using modified version of example: https://github.com/raspberrypi/picamera2/blob/main/apps/app_capture2.py
Modified Version (added prints split capture and switch and changed logging to DEBUG mode):

-----------------------------------------------
#!/usr/bin/python3

# This example is essentially the same as app_capture.py, however here
# we use the Qt signal/slot mechanism to get a callback (capture_done)
# when the capture, that is running asynchronously, is finished.

from PyQt5 import QtCore
from PyQt5.QtWidgets import (QApplication, QHBoxLayout, QLabel, QPushButton,
                             QVBoxLayout, QWidget)

from picamera2 import Picamera2
from picamera2.previews.qt import QGlPicamera2
import datetime as dt

Picamera2.set_logging(Picamera2.DEBUG)

def post_callback(request):
    label.setText(''.join(f"{k}: {v}\n" for k, v in request.get_metadata().items()))

picam2 = Picamera2()
picam2.post_callback = post_callback
picam2.configure(picam2.create_preview_configuration(main={"size": (800, 600)}))

app = QApplication([])

def on_button_clicked():
    print('Button CLicked ', dt.datetime.now())
    button.setEnabled(False)
    cfg = picam2.create_still_configuration()
    print('Switch Mode ', dt.datetime.now())
    picam2.switch_mode(cfg)
    print('Capture ', dt.datetime.now())
    picam2.capture_file("test.jpg", signal_function=qpicamera2.signal_done)
    print('Job started ', dt.datetime.now())

def capture_done(job):
    picam2.wait(job)
    print('Job completed ', dt.datetime.now())
    button.setEnabled(True)

qpicamera2 = QGlPicamera2(picam2, width=800, height=600, keep_ar=False)
button = QPushButton("Click to capture JPEG")
label = QLabel()
window = QWidget()
qpicamera2.done_signal.connect(capture_done)
button.clicked.connect(on_button_clicked)

label.setFixedWidth(400)
label.setAlignment(QtCore.Qt.AlignTop)
layout_h = QHBoxLayout()
layout_v = QVBoxLayout()
layout_v.addWidget(label)
layout_v.addWidget(button)
layout_h.addWidget(qpicamera2, 80)
layout_h.addLayout(layout_v, 20)
window.setWindowTitle("Qt Picamera2 App")
window.resize(1200, 600)
window.setLayout(layout_h)

picam2.start()
window.show()
app.exec() 

-----------------------------------------------

**Expected behaviour**

Expected behavior is that the image is taken, but immediate would be a mode switch

**Console Output, Screenshots**
If applicable, any console output or screenshots that show the problem and associated error messages.

The output of the above code is:
-----------------------------------------------
felix@reterminal:~ $ python ~/Camera/minimal_set_up.py 
[0:14:48.572749876] [2356]  INFO Camera camera_manager.cpp:299 libcamera v0.0.0+4186-d1dc0373
[0:14:48.576868240] [2360]  WARN CameraSensorProperties camera_sensor_properties.cpp:205 No static properties available for 'arducam_64mp'
[0:14:48.576922702] [2360]  WARN CameraSensorProperties camera_sensor_properties.cpp:207 Please consider updating the camera sensor properties database
[0:14:48.599857197] [2360]  WARN RPI raspberrypi.cpp:1308 Mismatch between Unicam and CamHelper for embedded data usage!
[0:14:48.600867668] [2360]  INFO RPI raspberrypi.cpp:1425 Registered camera /base/soc/i2c0mux/i2c@0/arducam_64mp@1a to Unicam device /dev/media0 and ISP device /dev/media2
picamera2.picamera2 INFO: Initialization successful.
picamera2.picamera2 INFO: Camera now open.
picamera2.picamera2 DEBUG: <libcamera._libcamera.CameraManager object at 0x7f9ccea170>
picamera2.picamera2 DEBUG: Requesting configuration: {'use_case': 'preview', 'transform': <libcamera.Transform 'identity'>, 'colour_space': <libcamera.ColorSpace 'Rec709'>, 'buffer_count': 4, 'queue': True, 'main': {'format': 'XBGR8888', 'size': (800, 600), 'stride': 3200, 'framesize': 1920000}, 'lores': None, 'raw': None, 'controls': {'NoiseReductionMode': <NoiseReductionModeEnum.Minimal: 3>, 'FrameDurationLimits': (100, 83333)}, 'display': 'main', 'encode': 'main'}
picamera2.picamera2 INFO: Camera configuration has been adjusted!
[0:14:48.609221541] [2356]  INFO Camera camera.cpp:1028 configuring streams: (0) 800x600-XBGR8888
[0:14:48.609691499] [2360]  INFO RPI raspberrypi.cpp:805 Sensor: /base/soc/i2c0mux/i2c@0/arducam_64mp@1a - Selected sensor format: 1280x720-SBGGR10_1X10 - Selected unicam format: 1280x720-pBAA
picamera2.picamera2 INFO: Configuration successful!
picamera2.picamera2 DEBUG: Final configuration: {'use_case': 'preview', 'transform': <libcamera.Transform 'identity'>, 'colour_space': <libcamera.ColorSpace 'Rec709'>, 'buffer_count': 4, 'queue': True, 'main': {'format': 'XBGR8888', 'size': (800, 600), 'stride': 3200, 'framesize': 1920000}, 'lores': None, 'raw': None, 'controls': {'NoiseReductionMode': <NoiseReductionModeEnum.Minimal: 3>, 'FrameDurationLimits': (100, 83333)}, 'display': 'main', 'encode': 'main'}
picamera2.picamera2 DEBUG: Streams: {'main': <libcamera._libcamera.Stream object at 0x7f9c62b530>, 'lores': None, 'raw': None}
picamera2.picamera2 DEBUG: Allocated 4 buffers for stream 0.
picamera2.picamera2 INFO: Camera started
Button CLicked  2023-03-13 12:10:33.377366
Switch Mode  2023-03-13 12:10:33.379489
^CTraceback (most recent call last):
  File "/home/felix/Camera/minimal_set_up.py", line 34, in on_button_clicked
    picam2.switch_mode(cfg)
  File "/home/felix/.local/lib/python3.9/site-packages/picamera2/picamera2.py", line 1218, in switch_mode
    return self.dispatch_functions(functions, wait, signal_function)
  File "/home/felix/.local/lib/python3.9/site-packages/picamera2/picamera2.py", line 1166, in dispatch_functions
    return job.get_result() if wait else job
  File "/home/felix/.local/lib/python3.9/site-packages/picamera2/job.py", line 77, in get_result
    return self._future.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 435, in result
    self._condition.wait(timeout)
  File "/usr/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
KeyboardInterrupt
-----------------------------------------------

**Hardware :**
 Please state what kind of Pi you are using, and what camera is attached.

Im using a CM4 inside a reTerminal (different IO board with attached lcd touchscreen) with a 64MP arducam of which I removed the autofocus lens (hasnt impacted behavior with libcamera)

CMA is set to 512 

The camera preview works fine, imaging without preview works fine.

**Additional context**

The buffer generally fails to allocate if one does not specify --imediate (on full resolution that is) for the libcamera-still command. It is not always required but mostly

I managed to solve this issue by closing and removing all camera instances - however this raised a new issue. The code for doing so is:

self.qpcamera.cleanup()
self.Preview.removeWidget(self.qpcamera)
del self.qpcamera       
self.camera.stop()                     
self.camera.close()
del self.camera

And then restarting the camera with a still configuration, then after imaging killing it again, and reinitiating the preview mode. 

However, this only works for one image on the second image (ie changing as preview-> stil->image-> preview-> still -> image), buffers fail to allocate.
I assume in this case I didnt fully  "Reset" the camera.

I will attempt to utilize  the cmd line for taking the still images with the cmd:
libcamera-still --hdr=0 -v --datetime --autofocus-on-capture=0 --autofocus-mode=manual --denoise=off --gain=10 --nopreview --shutter=1000000 --flush=1 --ev=0 -t 100000 --immediate
instead of switching to still but still closing all instances in python

**Comment by davidplowman** [comment]
Hi, am I right in thinking you're using an Arducam 64MP camera? I assume the problems are due to the very large amounts of memory that this camera may require, but I can't really confirm that as I don't have one here. You would probably need to talk to the module vendor for more support.

Sorry not to be more helpful. But we are hoping to make a release soon which uses less CMA memory, so maybe this will help you.

**Comment by Naderschah** [comment]
Hey,
It is indeeed the 64MP camera.
I managed to get it working by using the cmd line implementation to take an image,
this makes me think that there is some link or something within the camera that doesnt get reset the way I remove the camera.
Would you happen to know how I can fully release the camera as happens when python does its cleanup (or what to look for in your source code to find it)?

Also would you happen to know if its theoretically possible to set cma to 1024? Everytime i try it assigns 300 something.

**Comment by davidplowman** [comment]
The command line applications are able to use YUV420 rather than RGB, so the image buffers are much smaller. Unfortunately most Python modules don't support YUV420. You might consider capturing YUV420 instead and then using OpenCV to convert it to RGB. That would be a bit slow but the RGB buffer would be in user memory so wouldn't cause the same problems.

Calling `picam2.close()` should release everything. If it doesn't please send a minimal test script that demonstrates that the resources have not been freed, then we can take a look. Thanks.

So far as I know, 512MB is the largest for CMA.

**Comment by Naderschah** [comment]
Ah alright, thank you for the explanation and alternatives.
I will retry my method original method on the upcoming releases
