### ISSUE TITLE
[HOW-TO] get a non-rectified image

### ISSUE THREAD

**Issue by smetanadvorak** [raspberrypi/picamera2#630]
Hi!

Images that I get from my Camera Module 3 look rectified, i.e. lens distortion is already corrected: straight lines are straight (almost) and image is fit into a rectangle.

I would like to know how can I get the images with no rectification applied.

**Comment by sandyol55** [comment]
Distortion is not inevitable in a lens design.  If the specifier of the lens requires a low distortion lens and the designer has been given sufficient flexibility with regard to the other requirements then a low distortion lens is readily achievable.  Could it just be that the team at RPi have specified the V3 lenses in such a manner, and the designer/manufacturer has achieved the requirement?   ;-)

**Comment by davidplowman** [comment]
The Raspberry Pi does not apply any rectification, so anything that you're seeing must be happening inside the camera module (and indeed it may just be the lens). So I don't think there's anything that can be "disabled" here.

**Comment by smetanadvorak** [comment]
Thank you @davidplowman and @sandyol55.
From my experience, distortion is very noticeable in wide-angle lenses with physical size as small as this camera's. 

Here is an example image I've taken with my Camera Module 3. Straight lines tend to curve a bit towards the corners of the image, which looks like a rectification artifact to me.

![table](https://user-images.githubusercontent.com/2168635/227161466-a9c4a378-8236-4d61-b266-f1c45d9cc994.jpg)

However, I do see your point, especially considering that raw bayer images from this camera also come rectified. It would be an interesting twist to me if any software rectification was applied before de-bayering. 

Thank you for your answers, I'll keep this open for a moment, in case others have something to add.

**Comment by sandyol55** [comment]
Excellent example image! The residual distortion in the corners of the image is almost certainly optical in nature.
The lens design likely has a number of highly aspheric surfaces to help achieve the required performance in a low component count, compact design. The various orders of distortion correction contributions from the different surfaces, although extremely well balanced, don't completely cancel out across the entire field of view leaving some residual distortion. (Just a guess.) @davidplowman, I don't suppose the optical prescriptions of the Camera module lenses are openly available.

**Comment by smetanadvorak** [comment]
Thank you all, OK, I think I'll close the issue then. 

To summarize: there is no rectification step in raspberry camera modules.
