### ISSUE TITLE
[SUGGESTION] Set maximum allowable shutter speed

### ISSUE THREAD

**Issue by GuidoBartoli** [raspberrypi/picamera2#634]
**Is your feature request related to a problem? Please describe.**
Using the `picamera2` API, I did not find a way to set a maximum shutter time while retaining the AGC algorithm.

**Describe the solution you'd like**
The camera controls should expose the `"AeMaxShutter"` parameter to be set by `set_controls()` method equivalent to the `SetMaxShutter()` method from `AgcAlgorithm` class API detailed in the [Camera Algorithm and Tuning Guide](https://datasheets.raspberrypi.com/camera/raspberry-pi-camera-guide.pdf) (page 29).

**Describe alternatives you've considered**
For my application, I need the maximum exposure time to be no more than 1/400 s to avoid motion blur when capturing a moving object. However, I would also like that, if the lighting is sufficient, the AGC algorithm can use shorter times and smaller analog gains to avoid overexposure (a behavior similar to the "Auto-ISO" mode with the "Min shutter" option enabled in traditional cameras).

Since the default `"short"` exposure mode allows the shutter time to climb up to 120000 us (~1/8 s), I had to manually set the values of `exposure_modes` within the JSON tuning file to set an upper limit. This is how I changed the `"short"` mode to achieve a maximum shutter time of 1/400 s:
```
"short":
{
    "shutter": [ 100, 600, 1000, 1500, 2000, 2500 ],
    "gain": [ 1.0, 2.0, 3.0, 4.0, 5.0, 6.0 ]
}
```

**Additional context**
Nothing to add.

**Comment by davidplowman** [comment]
Hi, indeed libcamera does not have a control for setting the max shutter, but for Raspberry Pi sensors we define this in the tuning file. Editing the tuning file would be the correct thing to do.

**Comment by GuidoBartoli** [comment]
Does the tuning file expose a `max_shutter` value or it is a consequence of changing exposure modes as I did?

**Comment by GuidoBartoli** [comment]
> **Describe the solution you'd like** The camera controls should expose the `"AeMaxShutter"` parameter to be set by `set_controls()` method equivalent to the `SetMaxShutter()` method from `AgcAlgorithm` class API detailed in the [Camera Algorithm and Tuning Guide](https://datasheets.raspberrypi.com/camera/raspberry-pi-camera-guide.pdf) (page 29).

Is there any news about the equivalent in `picamera2` (Python) of the SetMaxShutter() function of `libcamera` (C++)? Both _Raspberry Pi 5_ and the _Global Shutter Camera_ have recently come out, but still this functionality does not seem to be present in the latest version of picamera2.
