### ISSUE TITLE
[HOW-TO] Record videos to the disk while using openCV

### ISSUE THREAD

**Issue by amansoo** [raspberrypi/picamera2#638]
I am using openCV and picamera2 together for a a project. Basically, once motion is detected from a PIR sensor I record a 30 second video with picamera2 and save it to the disk. When it reaches that point in the code, it crashes with the error
RuntimeError: Camera already started
I went through this github repo and found another function which does the same job (easy_video.py) and it worked for the most part (it didn't crash) but it hanged after the recording was done. The video got saved successfully but it stopped at that point indefinitely.  This is my code:
```
import cv2
import RPi.GPIO as GPIO
import time
from picamera2.encoders import H264Encoder
from picamera2.outputs import FfmpegOutput
from picamera2 import Picamera2
pi_cam = Picamera2()
pi_cam.preview_configuration.main.size=(1080, 720) # largest 1920, 1080
pi_cam.preview_configuration.main.format="RGB888" # to comply with opencv
pi_cam.preview_configuration.align() # finds the closest standard
# size to the one asked in preview.size. This is done for performance
pi_cam.configure("preview")
capture_config = pi_cam.create_still_configuration() #the con-
# fig for capturing images 
encoder = H264Encoder(10000000)
pi_cam.start()
GPIO.setmode(GPIO.BCM)
pir_pin = 18 # BCM numbering
GPIO.setup(18, GPIO.IN)
time.sleep(10) # we sleep so that the pir sensor is able to
# sketch the surroundings and the average background IR.
print("PIR sensor ready to go")
try:
    while True:
        motion = GPIO.input(pir_pin)
        print(motion)
        if motion == 1:
            #pi_cam.switch_mode_and_capture_file(capture_config, "image.jpg")
            #time.sleep(1)
            #pi_cam.start_recording(encoder, 'intruder.h264', Quality.HIGH)
            #time.sleep(5)
            #pi_cam.stop_recording()
            #pi_cam.start_and_record_video("test.mp4", duration=5)
            pi_cam.start_recording(encoder, 'test.h264')
            time.sleep(10)
            pi_cam.stop_recording()
        frame = pi_cam.capture_array() # grabbing a frame
        cv2.imshow("Camera Feed", frame)
        if cv2.waitKey(1) == ord("q"):
            break
        motion = 0
except KeyboardInterrupt:
    GPIO.cleanup()
    cv2.destroyAllWindows()
    print("GPIO cleaned")


```
I believe the problem is in line 16
```
pi_cam.start()

```
I tried removing that line but then the video output would stop from opencv. You would be right to think that I do not need the feed from openCV and if it comes to that I will remove the feed but wondering if there is a way to make it work without needing to remove openCV feed.
Thanks,
Aman

**Comment by tvoverbeek** [comment]
Start_recording() and stop_recording also start respectively stop the camera, hence the "RuntimeError: Camera already started"
Use start_encoder90 and stop_encoder() instead.

Why do you use cv2 for the preview instead of the picamera2 preview window?
