### ISSUE TITLE
[HOW-TO] which libcamera version library supports all autofocus commands?

### ISSUE THREAD

**Issue by millermuttu** [raspberrypi/picamera2#640]
I am trying to implement all the features of autofocus in my project.

Please suggest which libcamera version will be supported with picamera2 0.3.8 version

**Comment by tvoverbeek** [comment]
First you need picamera2 0.3.9 for autofocus.
If you do `apt show python3-picamera2`you find under the dependencies:
'python3-libcamera (>= 0~git20230302+923f5d70-1)'
=> libcamera version: `0~git20230302+923f5d70`

**Comment by davidplowman** [comment]
Hi, I'll close this issue for now as I don't think there's anything specific for us to investigate. But do please open another issue if you are still having problems. Thanks!
