### ISSUE TITLE
[BUG] Horizontal banding artifacts

### ISSUE THREAD

**Issue by GuidoBartoli** [raspberrypi/picamera2#644]
**Describe the bug**

**To Reproduce**
I made a script to set up the camera, capture and save frames continuously with the following configuration: 
```
Buffer: 6
Queue: True
Resolution: 2304 x 1296
Flipping: "both"
Exposure mode: "short"
Exposure metering: "center"
Histogram constraint: "normal"
Exposure compensation: 0
White balance: "auto"
Auto-focus: "manual"
Lens position: 0
```
Following #634, I am using this custom exposure mode to ensure that the maximum shutter time is 1/400s:
```
{
    "shutter": [ 100, 600, 1000, 1500, 2000, 2500 ],
    "gain": [ 1.0, 1.0, 2.0, 2.0, 3.0, 3.0 ]
}
```

Since I needed associated metadata, frames are captured using requests inside the loop:
```
request = self.capture_request()
frame, metadata = request.make_array("main"), request.get_metadata()
request.release()
``` 

**Expected behaviour**
The acquired images should be free of visual artifacts.

**Console Output, Screenshots**
Most of the frames have the artifacts that you can see in the following images (the camera is pointed at the floor and frames tiles).
![000028](https://user-images.githubusercontent.com/16103676/228587625-9a587a3e-4a12-4517-b649-531cbe967f56.jpg)
![000029](https://user-images.githubusercontent.com/16103676/228587667-3c9330e0-30b0-4350-bba1-d619f2d6594a.jpg)
![000029_1](https://user-images.githubusercontent.com/16103676/228587694-e097f1c0-1a6c-4122-8600-eb7b60345d6b.jpg)

**Hardware :**
*Board*: Raspberry Pi 4 (4 GB)
*Camera*: Camera Module 3 Wide NoIR
*OS*: Raspberry Pi OS Lite (Bullseye)
*Python*: v3.9.2

**Comment by davidplowman** [comment]
Hi, it would be good to try and find out a bit more about where this is coming from. I notice slightly dark halos around the artifacts which somewhat suggests it's in the raw sensor data that is being fed to the ISP. Are you able to capture a DNG file where the JPEG has the problem, and we can check if it's in there too?

Also just wanted to check how long your ribbon cable is. Though bad connections often lead to a complete loss of sync and images go magenta, which would suggest that's not the problem. Have you noticed anything that correlates at all with the problem, such as the exposure times, or anything else?

**Comment by GuidoBartoli** [comment]
Thanks for answering, I share some additional findings about this issue.
- I had forgotten that this Raspberry Pi 4 is overclocked to 2.0 Ghz so I thought that was the cause, so I reset the ARM's default frequency, but the problem unfortunately remains
- I added a function to overlay metadata on the image, this is another one where artifacts are visible (_T = duration time, S = shutter time, A = analog gain, D = digital gain, L = measured lux_):
![000028](https://user-images.githubusercontent.com/16103676/228779738-6bffd2b7-a015-4cf1-91c0-8cdd6d50b138.jpg)
- I captured also the RAW image (you can download it from [here](https://www.dropbox.com/s/5tcwxx92ca1uube/raw.dng?dl=0)) with the same parameters adding `request.save_dng("raw.dng")` into my function and converted to 24bit with RawTherapee, but the artifacts are there too:
![raw](https://user-images.githubusercontent.com/16103676/228798042-c5eb53a3-d8e3-473e-83c4-0e7a877c9f7b.jpg)
- Here is the really very strange thing: I tried capturing a single image with the same setup using the command-line utility (`libcamera-jpeg -o foo.jpg --width 2304 --height 1296 --rotation 180 --shutter 2500 --analoggain 3 --autofocus-mode manual --lens-position 0 -t 1000`). I realize that this is a single capture unlike the other one which is in a capture cycle with video configuration, however I expected it to come out similar since the parameters are the same and instead it came out much darker, but without artifacts as you can see below:
![libcamera](https://user-images.githubusercontent.com/16103676/228789611-026f6049-fcc1-42ec-90ea-88b0f8fd0892.jpg)
- This is a picture of the Raspberry inside its case with the CSI connector coming to the Camera module mounted in front of it:
![camera](https://user-images.githubusercontent.com/16103676/228781354-736362dc-4bb8-4274-8632-eebdce9a35a5.jpg)

**Comment by GuidoBartoli** [comment]
The power supply is not a switching one, because the Raspberry is powered by [this Powerbank](https://it.rs-online.com/web/p/power-bank/2361455) which outputs 2.1A, however now I am testing with the official power supply connected to the wall, I will post the result here as soon as possible.

**Comment by davidplowman** [comment]
Hi, thanks for the raw file and information. It's interesting to note that the raw data shows the same problem so it's almost certainly some kind of transmission issue between the sensor and the Pi. I'd certainly be double-checking the cables, maybe try swapping them out, or looking for interference. I suppose a broken camera is possible though it feels less likely to me. As you say, double checking the power supply too sounds like a good move. Sorry not have anything more concrete to suggest.

**Comment by GuidoBartoli** [comment]
Thanks for coming back on this.

Unfortunately the issue is still present even with the official Raspberry Pi 4 power supply, so I think it is still related to the short custom exposures I explained above, because the more I increase the exposures, the less the number of artifact lines present in the image.

**Comment by davidplowman** [comment]
Have you been able to try another pi/cable/camera  (depending on whether any of these are available to you)?

**Comment by ryangrg** [comment]
I had this problem using a raspberry pi 4B and an arduocam HQ with switching IR filter. I unplugged and carefully plugged both ends of the connector ribbon back in and problem went away.

**Comment by GuidoBartoli** [comment]
> @GuidoBartoli what you seeing here is interference on signal, some information is here [raspberrypi/libcamera#43](https://github.com/raspberrypi/libcamera/issues/43)

Ok, thanks for the information!
