### ISSUE TITLE
[BUG] dtoverlay=rpi-ft5406 breaks camera with spyglass (picamera2) 

### ISSUE THREAD

**Issue by ubrider** [raspberrypi/picamera2#671]
**Describe the bug**
Hi, we just found an issue with a dev of spyglass (https://github.com/roamingthings/spyglass), that i need to add `dtoverlay=rpi-ft5406` to my "/boot/config.txt" for my touchscreen to be working correctly and flipped in direction with `touchscreen-inverted-x=1,touchscreen-inverted-y=1`, but it breaks the camera.

**To Reproduce**
Add `dtoverlay=rpi-ft5406` to "/boot/config.txt"

**Expected behaviour**
Cam should display an image and touchscreen should be working properly.

**Console Output, Screenshots**
```
@pi:~ $ libcamera-hello
Preview window unavailable
[0:01:13.471945943] [1344]  INFO Camera camera_manager.cpp:299 libcamera v0.0.4+22-923f5d70
ERROR: *** no cameras available ***
```

**Hardware :**
PI4b 4Gb, picam V3.

**Comment by davidplowman** [comment]
Hi, probably best to ask on the Camera forum as you'll get a wider audience there that can advise you on this kind of thing. Sorry not to be more help, but I don't know too much about these panels.

**Comment by ubrider** [comment]
ok nvm, It was mainly to adress an issue because i bypass the issue and resolved it. they told me to post here. :)
