### ISSUE TITLE
Metering for White Balance

### ISSUE THREAD

**Issue by Wied58** [raspberrypi/picamera2#7]
Could Picamera2 operate such that if white balance is supplied, the camera does not meter for it decreasing the over imaging run time? I volunteer at a Planetarium and we use the existing PiCamera to image light pollution. As we want consistency in the images, we set white balance. We have started to experiment with image durations of up to 30 seconds and those run times are quite lengthy.

**Comment by davidplowman** [comment]
Yes, when you do `picam2.start()` you can instead do this `picam2.start({'ColourGains': (1.5, 2.5)})`. Clearly you can use whatever fixed values you like in place of 1.5 and 2.5. If the camera is running and you want to query the current colour gains, you can do `picam2.capture_metadata()['ColourGains']`. You can also fix the exposure time (`'ExposureTime'`) and gain (`'AnalogueGain'`) if you want.

**Comment by Wied58** [comment]
Thank you,

Will manually setting the gains, stop PiCamera2 from taking the time to determine them?

**Comment by davidplowman** [comment]
> Will manually setting the gains, stop PiCamera2 from taking the time to determine them?

Yes, that's correct.

**Comment by davidplowman** [comment]
Please feel free to open another issue if you have more questions. Thanks!
