### ISSUE TITLE
[DOCUMENTATION] typo in section 4.2.1.5, second paragraph.

### ISSUE THREAD

**Issue by Vincent-Stragier** [raspberrypi/picamera2#729]
In section 4.2.1.5 More on the display stream, second paragraph, is written:

`This would reqest a full resolution main stream, [...]`

Instead of:

`This would request a full resolution main stream, [...]`

**Comment by davidplowman** [comment]
Hi, thanks for pointing that out. I've fixed the documentation source so that should filter through "in a little while".
