### ISSUE TITLE
[DOCUMENTATION] missing a colour space in the example (4.2.1.2. More on colour spaces)

### ISSUE THREAD

**Issue by Vincent-Stragier** [raspberrypi/picamera2#731]
Hi,

In the subsection 4.2.1.2. More on colour spaces, an example is given followed by:
`These are in fact the only colour spaces supported by the Pi’s camera system. [...]`

However, in the example, only the `sYCC` and `Rec709` are shown. Later, in the Appendix B, in the table 5, for the parameter `colour_space`, we can see three permitted values: `Sycc()`, `Smpte170m()` and `Rec709()`.

I think the colour space `Smpte170m()` should be added in the example.

Regards,
Vincent

**Comment by davidplowman** [comment]
Thanks for pointing this out. I've added the missing colour space, it will appear in the published version in due course...
