### ISSUE TITLE
[DOCUMENTATION] strange wording in section 5.1. Camera controls

### ISSUE THREAD

**Issue by Vincent-Stragier** [raspberrypi/picamera2#732]
Hi,

In the section 5.1. Camera controls, we can read at the end of the 5th paragraph:
` The default value should be interpreted with some caution as in many cases libcamera’s default value will
long since have been overwritten by the camera tuning once the camera is started.`

I'm not a native English speaker, however, I think some words have been misplaced. Shouldn't it be something like that? `will have long since been`:
`The default value should be interpreted with some caution, as in many cases, libcamera’s default value will have long since been overwritten by the camera tuning once the camera is started.`

Regards,
Vincent

**Comment by davidplowman** [comment]
Hi, thanks for this. To be honest the first version reads OK to me but I agree the whole thing is slightly awkward.

So instead, I've suggested to the documentation team that we use this: "... libcamera's default value will be overwritten by the camera tuning as soon as the camera is started." Let's see what happens!
