### ISSUE TITLE
[BUG] Multi-encoder recording issue

### ISSUE THREAD

**Issue by azsde** [raspberrypi/picamera2#738]
Hello,

When using two encoders and triggering a recording using "picam2.start_recording" ,when stopping the recording using "picam2.stop_recording()"  it will stop every encoders:

```
picam2 = Picamera2()
video_config = picam2.create_video_configuration()
picam2.configure(video_config)

mjpegEncoder = MJPEGEncoder()
h264encoder = H264Encoder()

picam2.start_encoder(mjpegEncoder)
picam2.start()

picam2.start_recording(h264encoder, "output.h264", quality=Quality.VERY_HIGH)
sleep(10)
picam2.stop_recording()

# From here, mjpegEncoder is not usable anymore as it has been stopped when calling picam2.stop_recording().
# The workaround is to call "stop_encoder(h264encoder)" instead of "picam2.stop_recording()"
```

**Comment by davidplowman** [comment]
Hi, I think it's intentional that `stop_recording()` stops everything. I would probably create the outputs explicitly and then you can stop one and not the other. Maybe section 9.3 of [the manual ](https://datasheets.raspberrypi.com/camera/picamera2-manual.pdf)might help?

**Comment by azsde** [comment]
Hi,

Thank you for your answer.

I based my code on the examples, which seem to have a different approach than the one in the section 9.3.

Your advice would be to use the outputs directly then ?

**Comment by RedBlaze42** [comment]
Hi,
You can stop only one encoder by using
`picam2.stop_encoder(encoders=mjpegEncoder)`
or
`picam2.stop_encoder(encoders=h264encoder)`
Depending on what you want
