### ISSUE TITLE
Picamera2 with raspberry pi global shutter camera returns one color background image instead of the real image

### ISSUE THREAD

**Issue by aymeric75** [raspberrypi/picamera2#791]
Hello,

I have a **raspberry pi global shutter camera**  on a  raspberry pi 4 model B

I ran this code:
```
#!//usr/bin/python3

from picamera2 import Picamera2

picam2 = Picamera2()
config = picam2.create_still_configuration()
picam2.configure(config)

picam2.start()

np_array = picam2.capture_array()
print(np_array)
picam2.capture_file("demo.jpg")
picam2.stop()

```

And it produces this image:

![Sans titre](https://github.com/raspberrypi/picamera2/assets/12927600/4228f3dd-36c2-414c-947e-502c1dac9fa0)

**Comment by aymeric75** [comment]
yes it does, I am wondering, is having a lens mandatory ? because I don't have one

**Comment by davidplowman** [comment]
Yes, you need to get a lens of some sort, maybe like this https://thepihut.com/products/raspberry-pi-high-quality-camera-lens (other lenses and suppliers are available, this is just one example)

**Comment by aymeric75** [comment]
so, the problem comes from the fact that I don't have a lens ? thanks

**Comment by sam598** [comment]
Yes. All cameras need lenses.

An image sensor by itself will just capture all of the light that hits it. Lenses focus the light into a coherent image.

https://en.wikipedia.org/wiki/Camera_lens

The one exception would be if you create a pinhole camera, but even then the pinhole is considered a lens.

https://en.wikipedia.org/wiki/Pinhole_camera

**Comment by aymeric75** [comment]
Hello, I have put the lens, but it now returns a black image

**Comment by davidplowman** [comment]
Hi, could you please double-check that you've opened the lens aperture. Might it be possible to attach a small image of your Pi and the connected camera? Thanks.

**Comment by aymeric75** [comment]
Ok, I found the solution, it was a matter of setting the lens (more light, more focus)
