### ISSUE TITLE
[OTHER] start_encoder() needs a parameter?

### ISSUE THREAD

**Issue by baqwas** [raspberrypi/picamera2#802]
**Please only include one item/question/problem per issue!**
Reference: The _examples_ section, the script **capture_circular.py** near line 20:

The following statement did not work for me:
`picam2.start_encoder()`
However, the following change worked:
`picam2.start_encoder(encoder)`

Regards.

P.S.
Apologies for not submitting a pull request. I'm still learning how to use GitHub productively.

**Comment by davidplowman** [comment]
Hi, thanks for the report. Yes, it seems we aren't running some of those as part of our CI test suite because it runs forever! There are a few others to fix up as well, so thanks again for letting us know.

**Comment by baqwas** [comment]
Will continue to step through the examples one script at a time (alphabetical order, of course). Hopefully, I'll learn a little bit about Picamera2 too in the process.

Regards.
