### ISSUE TITLE
[HOW-TO] capture a full resolution still during video

### ISSUE THREAD

**Issue by marcofariasmx** [raspberrypi/picamera2#841]
**Describe what it is that you want to accomplish**
Take a full resolution still picture during a video stream.
Based on these examples so far: 

1) Still during vid: https://github.com/raspberrypi/picamera2/blob/main/examples/still_during_video.py

2) Full resolution picture: https://github.com/raspberrypi/picamera2/blob/main/examples/capture_dng_and_jpeg.py

**Describe alternatives you've considered**
1) Saving a DNG file from the raw stream and then converting that DNG to a JPG. The results are not so great colorwise, cpu expensive and prone to sd memory wear. Was not able get success with the .save_dng() method and io.BytesIO() to save to memory while converting to JPG.

2) Capturing an array and saving it to an image

```
raw = picam2.capture_array("raw")
print(raw.shape)
array = np.array(raw)

array = array.astype(np.uint8)

# Convert the Bayer pattern to RGB
rgb = cv2.cvtColor(array, cv2.COLOR_BayerBG2BGR) 

# If you want to save the result:
cv2.imwrite('static/converted_image1.jpg', rgb)
```

Did not work either, instead got weird picture results related to these topics 
https://github.com/raspberrypi/picamera2/issues/594
https://github.com/raspberrypi/picamera2/issues/712

![converted_image1](https://github.com/raspberrypi/picamera2/assets/41245794/05f250c7-7ed7-4576-880c-ef0ccd62a3fa)
![converted_image (1)](https://github.com/raspberrypi/picamera2/assets/41245794/ab5ad3ab-d291-4b67-9aec-45e2231d398d)
![test_img](https://github.com/raspberrypi/picamera2/assets/41245794/5a66784f-f411-4835-ad1b-1dd37c1358c1)

**Additional context**
Not interested in high FPS or anything similar, just a low quality video stream used for live time monitoring and 1 HQ full resolution picture every minute.

Current code: https://github.com/marcofariasmx/Raspberry-Picamera2-Surveillance/blob/main/flask_picam2_stream_and_pic.py

**Comment by davidplowman** [comment]
Hi, thanks for the question. I haven't quite understood how the "still_during_video.py" example isn't the right answer. It's true that this isn't the full sensor resolution, but you are fundamentally restricted by the size being output by the sensor for the video. You _could_ run the camera at full resolution, and this would give you the full sensor resolution for your stills, but your video would be limited to 10fps (or whatever framerate the system supports for that resolution).

**Comment by marcofariasmx** [comment]
Thank you for your reply @davidplowman 

The thing is I am not able to take a full res picture with the available encoders in a Raspberry Pi Zero 2 W.

I've tried with the following code:

`#!/usr/bin/python3

import time

from picamera2 import Picamera2
from picamera2.encoders import H264Encoder

# Encode a VGA stream, and capture a higher resolution still image half way through.

picam2 = Picamera2()
full_resolution = picam2.sensor_resolution
half_resolution = [dim // 2 for dim in full_resolution]

print("Sensor resolution: ")
print(full_resolution)

main_stream = {"size": full_resolution}
lores_stream = {"size": (640, 480)}
video_config = picam2.create_video_configuration(main_stream, lores_stream, encode="lores")
picam2.configure(video_config)

encoder = H264Encoder()

picam2.start_recording(encoder, 'test.h264')
time.sleep(5)

# It's better to capture the still in this thread, not in the one driving the camera.
request = picam2.capture_request()
request.save("main", "test.jpg")
request.release()
print("Still image captured!")

time.sleep(5)
picam2.stop_recording()`

And I get this error:
![image](https://github.com/raspberrypi/picamera2/assets/41245794/4a153f91-d8f1-4ebb-a8ec-4a66a71e9c04)

Then I replaced the H264Encoder for the JpegEncoder and I got this error:
![image](https://github.com/raspberrypi/picamera2/assets/41245794/94da519d-119f-47c8-9c91-518bc0d62854)

Then I replaced the encoder for the MJPEGEncoder and got the same error as the last one:
![image](https://github.com/raspberrypi/picamera2/assets/41245794/f86a5036-821b-49cd-8fe2-dd6ab9e9c83d)

Same for the rest of encoders.

Not really sure what other settings to change or which would be the appropiate encoder. I understand that H264 is not an option since it is limited to 1920 x 1280.

Any further advice or guidance would be highly appreciated.

**Comment by marcofariasmx** [comment]
I've also tried changing the CMA settings to the following in the config.txt file 
'''
# Enable DRM VC4 V3D driver
dtoverlay=vc4-kms-v3d,cma-400
max_framebuffers=2
'''

but it seems that the max amount that the system would allow is half which is 256. I've also tried increasing and decreasing the max_framebuffers with no success

**Comment by davidplowman** [comment]
Hi, thanks for posting some code. Am I right in thinking it's trying to use a video configuration with 12MP buffers? By default it tries to allocate 8 of these buffers, and they'll be 32-bit RGBA each. I don't think that's ever going to work.

I would suggest reducing the `buffer_count`. You'll need at least 2 to avoid frame drops all over the place, maybe 3. Generally higher `buffer_count` means fewer frame drops, but if you're running the sensor at 12MP then you won't get that high a framerate anyway.

Also set the main stream format to `'RGB888'` (or `'BGR888'`), this is a bit less bad than the 32-bit format. You only need the 32-bit version if you want a preview window.

Finally try `cma-384`.

**Comment by marcofariasmx** [comment]
Thank you very much, with your suggestions it finally worked! I will proceed to close this issue.

In case anyone is wondering how or faces the same deal, here is the code that worked:


```
#!/usr/bin/python3

import time

from picamera2 import Picamera2
from picamera2.encoders import JpegEncoder, MJPEGEncoder, H264Encoder

# Encode a VGA stream, and capture a higher resolution still image half way through.

picam2 = Picamera2()
full_resolution = picam2.sensor_resolution
half_resolution = [dim // 2 for dim in full_resolution]

print("Sensor resolution: ")
print(full_resolution)

main_stream = {"size": full_resolution, "format": "RGB888"}
lores_stream = {"size": (640, 480)}
video_config = picam2.create_video_configuration(main_stream, lores_stream, encode="lores", buffer_count=2)
picam2.configure(video_config)

encoder = MJPEGEncoder()

picam2.start_recording(encoder, 'test.mjpeg')
time.sleep(5)

# It's better to capture the still in this thread, not in the one driving the camera.
request = picam2.capture_request()
request.save("main", "test.jpg")
request.release()
print("Still image captured!")

time.sleep(5)
picam2.stop_recording()
```
