### ISSUE TITLE
[HOW-TO] UDP server h264 format

### ISSUE THREAD

**Issue by blukky** [raspberrypi/picamera2#992]
How to write a server for receiving and displaying a video stream received over udp and encoded in h264 format, as is done in the example for sending a video stream over udp

**Comment by davidplowman** [comment]
Hi, thanks for the question. Do the suggestions [here](https://www.raspberrypi.com/documentation/computers/camera_software.html#udp) help?

Note that I would recommend ffplay over vlc these days; recent versions of vlc don't handle vanilla h264 streams properly.
