### ISSUE TITLE
[HOW-TO] Recording motion vector data

### ISSUE THREAD

**Issue by Tuxliri** [raspberrypi/picamera2#994]
In Picamera 1.x.x existed a class [PiMotionArray](https://picamera.readthedocs.io/en/release-1.13/api_array.html#picamera.array.PiMotionArray) that output the motion vectors of the camera stream as obtained from the h264 encoder.
I couldn't find this class anymore in PiCamera2, is there an equivalent in the library or another option to obtain the motion vector from the h264 encoder, without having to explicitly compute them on the CPU?

**Comment by davidplowman** [comment]
We've been moving over to using standard Linux (V4L2)  APIs for things like video encoders, camera devices, and so on. Unfortunately there are no standard V4L2 APIs to access motion vector data so far as I know, so this feature is no longer available.

**Comment by Tuxliri** [comment]
I see, that's unfortunate, it was a useful feature.
